class AlphabetLetter {
  final String char;
  final String name;
  final String soundLike;
  final String example;
  const AlphabetLetter(this.char, this.name, this.soundLike, this.example);
}

class AlphabetData {
  static const ar = <AlphabetLetter>[
    AlphabetLetter('ا', 'Elif', 'a', 'أب'),
    AlphabetLetter('ب', 'Ba', 'b', 'باب'),
    AlphabetLetter('ت', 'Ta', 't', 'تمر'),
    AlphabetLetter('ث', 'Se', 'th', 'ثلج'),
    AlphabetLetter('ج', 'Cim', 'j', 'جمل'),
    AlphabetLetter('ح', 'Ha', 'h derin', 'حب'),
    AlphabetLetter('خ', 'Hı', 'kh', 'خبز'),
    AlphabetLetter('د', 'Dal', 'd', 'دار'),
    AlphabetLetter('ذ', 'Zel', 'dh', 'ذهب'),
    AlphabetLetter('ر', 'Ra', 'r', 'رأس'),
    AlphabetLetter('ز', 'Ze', 'z', 'زيت'),
    AlphabetLetter('س', 'Sin', 's', 'سلام'),
    AlphabetLetter('ش', 'Şın', 'sh', 'شمس'),
    AlphabetLetter('ص', 'Sad', 's kalın', 'صباح'),
    AlphabetLetter('ض', 'Dad', 'd kalın', 'ضوء'),
    AlphabetLetter('ط', 'Tı', 't kalın', 'طبيب'),
    AlphabetLetter('ظ', 'Zı', 'z kalın', 'ظهر'),
    AlphabetLetter('ع', 'Ayn', 'a gırtlak', 'عين'),
    AlphabetLetter('غ', 'Ğayn', 'gh', 'غدا'),
    AlphabetLetter('ف', 'Fe', 'f', 'فم'),
    AlphabetLetter('ق', 'Kaf', 'q', 'قلب'),
    AlphabetLetter('ك', 'Kef', 'k', 'كتاب'),
    AlphabetLetter('ل', 'Lam', 'l', 'ليل'),
    AlphabetLetter('م', 'Mim', 'm', 'ماء'),
    AlphabetLetter('ن', 'Nun', 'n', 'نور'),
    AlphabetLetter('ه', 'He', 'h', 'هذا'),
    AlphabetLetter('و', 'Vav', 'w/u', 'ورد'),
    AlphabetLetter('ي', 'Ye', 'y/i', 'يد'),
  ];

  static const ru = <AlphabetLetter>[
    AlphabetLetter('А', 'A', 'a', 'мама'),
    AlphabetLetter('Б', 'Be', 'b', 'брат'),
    AlphabetLetter('В', 'Ve', 'v', 'вода'),
    AlphabetLetter('Г', 'Ge', 'g', 'город'),
    AlphabetLetter('Д', 'De', 'd', 'дом'),
    AlphabetLetter('Е', 'Ye', 'ye', 'еда'),
    AlphabetLetter('Ё', 'Yo', 'yo', 'ёлка'),
    AlphabetLetter('Ж', 'Je', 'zh', 'жизнь'),
    AlphabetLetter('З', 'Ze', 'z', 'зима'),
    AlphabetLetter('И', 'İ', 'i', 'имя'),
    AlphabetLetter('Й', 'İ kratkoye', 'y', 'чай'),
    AlphabetLetter('К', 'Ka', 'k', 'кофе'),
    AlphabetLetter('Л', 'El', 'l', 'лес'),
    AlphabetLetter('М', 'Em', 'm', 'море'),
    AlphabetLetter('Н', 'En', 'n', 'ночь'),
    AlphabetLetter('О', 'O', 'o', 'окно'),
    AlphabetLetter('П', 'Pe', 'p', 'папа'),
    AlphabetLetter('Р', 'Er', 'r', 'рука'),
    AlphabetLetter('С', 'Es', 's', 'сон'),
    AlphabetLetter('Т', 'Te', 't', 'стол'),
    AlphabetLetter('У', 'U', 'u', 'утро'),
    AlphabetLetter('Ф', 'Ef', 'f', 'фильм'),
    AlphabetLetter('Х', 'Ha', 'kh', 'хлеб'),
    AlphabetLetter('Ц', 'Tse', 'ts', 'цвет'),
    AlphabetLetter('Ч', 'Çe', 'ch', 'чай'),
    AlphabetLetter('Ш', 'Şa', 'sh', 'школа'),
    AlphabetLetter('Щ', 'Şça', 'shch', 'щи'),
    AlphabetLetter('Ъ', 'Sert işaret', 'sessiz', 'объект'),
    AlphabetLetter('Ы', 'I', 'ı kalın', 'сын'),
    AlphabetLetter('Ь', 'Yumuşak işaret', 'yumuşatır', 'день'),
    AlphabetLetter('Э', 'E', 'e', 'это'),
    AlphabetLetter('Ю', 'Yu', 'yu', 'юг'),
    AlphabetLetter('Я', 'Ya', 'ya', 'яблоко'),
  ];

  static const ja = <AlphabetLetter>[
    AlphabetLetter('あ','a','a','あめ'), AlphabetLetter('い','i','i','いぬ'),
    AlphabetLetter('う','u','u','うみ'), AlphabetLetter('え','e','e','えき'),
    AlphabetLetter('お','o','o','おちゃ'), AlphabetLetter('か','ka','ka','かさ'),
    AlphabetLetter('き','ki','ki','き'), AlphabetLetter('く','ku','ku','くつ'),
    AlphabetLetter('け','ke','ke','け'), AlphabetLetter('こ','ko','ko','こども'),
    AlphabetLetter('さ','sa','sa','さかな'), AlphabetLetter('し','shi','shi','しろ'),
    AlphabetLetter('す','su','su','すし'), AlphabetLetter('せ','se','se','せんせい'),
    AlphabetLetter('そ','so','so','そら'), AlphabetLetter('た','ta','ta','たべる'),
    AlphabetLetter('ち','chi','chi','ちず'), AlphabetLetter('つ','tsu','tsu','つき'),
    AlphabetLetter('て','te','te','て'), AlphabetLetter('と','to','to','とり'),
    AlphabetLetter('な','na','na','なまえ'), AlphabetLetter('に','ni','ni','にほん'),
    AlphabetLetter('ぬ','nu','nu','ぬの'), AlphabetLetter('ね','ne','ne','ねこ'),
    AlphabetLetter('の','no','no','のむ'), AlphabetLetter('は','ha','ha','はな'),
    AlphabetLetter('ひ','hi','hi','ひと'), AlphabetLetter('ふ','fu','fu','ふね'),
    AlphabetLetter('へ','he','he','へや'), AlphabetLetter('ほ','ho','ho','ほん'),
    AlphabetLetter('ま','ma','ma','まど'), AlphabetLetter('み','mi','mi','みず'),
    AlphabetLetter('む','mu','mu','むし'), AlphabetLetter('め','me','me','め'),
    AlphabetLetter('も','mo','mo','もも'), AlphabetLetter('や','ya','ya','やま'),
    AlphabetLetter('ゆ','yu','yu','ゆき'), AlphabetLetter('よ','yo','yo','よる'),
    AlphabetLetter('ら','ra','ra','らいねん'), AlphabetLetter('り','ri','ri','りんご'),
    AlphabetLetter('る','ru','ru','るす'), AlphabetLetter('れ','re','re','れいぞうこ'),
    AlphabetLetter('ろ','ro','ro','ろく'), AlphabetLetter('わ','wa','wa','わたし'),
    AlphabetLetter('を','wo','o','を'), AlphabetLetter('ん','n','n','せん'),
  ];

  static const ko = <AlphabetLetter>[
    AlphabetLetter('ㄱ','giyeok','g/k','가방'), AlphabetLetter('ㄴ','nieun','n','나라'),
    AlphabetLetter('ㄷ','digeut','d/t','다리'), AlphabetLetter('ㄹ','rieul','r/l','라면'),
    AlphabetLetter('ㅁ','mieum','m','마음'), AlphabetLetter('ㅂ','bieup','b/p','바다'),
    AlphabetLetter('ㅅ','siot','s','사람'), AlphabetLetter('ㅇ','ieung','ng/-','아이'),
    AlphabetLetter('ㅈ','jieut','j','자전거'), AlphabetLetter('ㅊ','chieut','ch','차'),
    AlphabetLetter('ㅋ','kieuk','k','코'), AlphabetLetter('ㅌ','tieut','t','타다'),
    AlphabetLetter('ㅍ','pieup','p','파'), AlphabetLetter('ㅎ','hieut','h','하나'),
    AlphabetLetter('ㅏ','a','a','아기'), AlphabetLetter('ㅑ','ya','ya','야구'),
    AlphabetLetter('ㅓ','eo','eo','어머니'), AlphabetLetter('ㅕ','yeo','yeo','여자'),
    AlphabetLetter('ㅗ','o','o','오리'), AlphabetLetter('ㅛ','yo','yo','요리'),
    AlphabetLetter('ㅜ','u','u','우유'), AlphabetLetter('ㅠ','yu','yu','유리'),
    AlphabetLetter('ㅡ','eu','eu','음식'), AlphabetLetter('ㅣ','i','i','이름'),
    AlphabetLetter('ㅐ','ae','ae','애'), AlphabetLetter('ㅔ','e','e','네'),
    AlphabetLetter('ㅒ','yae','yae','얘'), AlphabetLetter('ㅖ','ye','ye','예'),
    AlphabetLetter('ㅘ','wa','wa','와'), AlphabetLetter('ㅙ','wae','wae','왜'),
    AlphabetLetter('ㅚ','oe','oe','외'), AlphabetLetter('ㅝ','wo','wo','워'),
    AlphabetLetter('ㅞ','we','we','웨'), AlphabetLetter('ㅟ','wi','wi','위'),
    AlphabetLetter('ㅢ','ui','ui','의'), AlphabetLetter('ㄲ','ssang giyeok','kk','꼬리'),
    AlphabetLetter('ㄸ','ssang digeut','tt','땅'), AlphabetLetter('ㅃ','ssang bieup','pp','빵'),
    AlphabetLetter('ㅆ','ssang siot','ss','쌀'), AlphabetLetter('ㅉ','ssang jieut','jj','짜다'),
  ];

  static const el = <AlphabetLetter>[
    AlphabetLetter('Α','Alfa','a','Αγάπη'), AlphabetLetter('Β','Vita','v','Βιβλίο'),
    AlphabetLetter('Γ','Gamma','gh','Γάλα'), AlphabetLetter('Δ','Delta','dh','Δρόμος'),
    AlphabetLetter('Ε','Epsilon','e','Εγώ'), AlphabetLetter('Ζ','Zita','z','Ζωή'),
    AlphabetLetter('Η','Ita','i','Ήλιος'), AlphabetLetter('Θ','Thita','th','Θάλασσα'),
    AlphabetLetter('Ι','Iota','i','Ιδέα'), AlphabetLetter('Κ','Kappa','k','Καφές'),
    AlphabetLetter('Λ','Lambda','l','Λόγος'), AlphabetLetter('Μ','Mi','m','Μάνα'),
    AlphabetLetter('Ν','Ni','n','Νερό'), AlphabetLetter('Ξ','Ksi','ks','Ξένος'),
    AlphabetLetter('Ο','Omikron','o','Όνομα'), AlphabetLetter('Π','Pi','p','Πόλη'),
    AlphabetLetter('Ρ','Ro','r','Ρόδο'), AlphabetLetter('Σ','Sigma','s','Σπίτι'),
    AlphabetLetter('Τ','Taf','t','Τραπέζι'), AlphabetLetter('Υ','Ipsilon','i','Ύπνος'),
    AlphabetLetter('Φ','Fi','f','Φως'), AlphabetLetter('Χ','Hi','h','Χέρι'),
    AlphabetLetter('Ψ','Psi','ps','Ψωμί'), AlphabetLetter('Ω','Omega','o','Ώρα'),
  ];

  static const he = <AlphabetLetter>[
    AlphabetLetter('א','Alef','sessiz/a','אבא'), AlphabetLetter('ב','Bet','b/v','בית'),
    AlphabetLetter('ג','Gimel','g','גמל'), AlphabetLetter('ד','Dalet','d','דלת'),
    AlphabetLetter('ה','He','h','הר'), AlphabetLetter('ו','Vav','v/u','ורד'),
    AlphabetLetter('ז','Zayin','z','זהב'), AlphabetLetter('ח','Het','h derin','חלון'),
    AlphabetLetter('ט','Tet','t','טל'), AlphabetLetter('י','Yod','y/i','יד'),
    AlphabetLetter('כ','Kaf','k/kh','כלב'), AlphabetLetter('ל','Lamed','l','לב'),
    AlphabetLetter('מ','Mem','m','מים'), AlphabetLetter('נ','Nun','n','נהר'),
    AlphabetLetter('ס','Samekh','s','סוס'), AlphabetLetter('ע','Ayin','gırtlak','עין'),
    AlphabetLetter('פ','Pe','p/f','פה'), AlphabetLetter('צ','Tsadi','ts','צפור'),
    AlphabetLetter('ק','Qof','k','קול'), AlphabetLetter('ר','Resh','r','ראש'),
    AlphabetLetter('ש','Shin','sh/s','שמש'), AlphabetLetter('ת','Tav','t','תודה'),
  ];

  static const hi = <AlphabetLetter>[
    AlphabetLetter('अ','a','a','अनार'), AlphabetLetter('आ','aa','aa','आम'),
    AlphabetLetter('इ','i','i','इमली'), AlphabetLetter('ई','ii','ii','ईख'),
    AlphabetLetter('उ','u','u','उल्लू'), AlphabetLetter('ऊ','uu','uu','ऊन'),
    AlphabetLetter('ए','e','e','एक'), AlphabetLetter('ऐ','ai','ai','ऐनक'),
    AlphabetLetter('ओ','o','o','ओखली'), AlphabetLetter('औ','au','au','औरत'),
    AlphabetLetter('क','ka','k','कम'), AlphabetLetter('ख','kha','kh','खाना'),
    AlphabetLetter('ग','ga','g','घर'), AlphabetLetter('घ','gha','gh','घर'),
    AlphabetLetter('च','cha','ch','चाय'), AlphabetLetter('छ','chha','chh','छत'),
    AlphabetLetter('ज','ja','j','जल'), AlphabetLetter('झ','jha','jh','झाड़ू'),
    AlphabetLetter('ट','ṭa','t retro','टमाटर'), AlphabetLetter('ठ','ṭha','th','ठंडा'),
    AlphabetLetter('ड','ḍa','d retro','डमरू'), AlphabetLetter('ढ','ḍha','dh','ढोल'),
    AlphabetLetter('त','ta','t','तल'), AlphabetLetter('थ','tha','th','थाली'),
    AlphabetLetter('द','da','d','दूध'), AlphabetLetter('ध','dha','dh','धन'),
    AlphabetLetter('न','na','n','नल'), AlphabetLetter('प','pa','p','पानी'),
    AlphabetLetter('फ','pha','ph','फल'), AlphabetLetter('ब','ba','b','बकरी'),
    AlphabetLetter('भ','bha','bh','भारत'), AlphabetLetter('म','ma','m','माता'),
    AlphabetLetter('य','ya','y','योग'), AlphabetLetter('र','ra','r','रात'),
    AlphabetLetter('ल','la','l','लड़का'), AlphabetLetter('व','va','v','वन'),
    AlphabetLetter('श','sha','sh','शहर'), AlphabetLetter('ष','ṣha','sh','षट्कोण'),
    AlphabetLetter('स','sa','s','सब'), AlphabetLetter('ह','ha','h','हाथ'),
  ];

  static const th = <AlphabetLetter>[
    AlphabetLetter('ก','ko kai','k','ไก่'), AlphabetLetter('ข','kho khai','kh','ไข่'),
    AlphabetLetter('ค','kho khwai','kh','ควาย'), AlphabetLetter('ง','ngo ngu','ng','งู'),
    AlphabetLetter('จ','cho chan','j','จาน'), AlphabetLetter('ช','cho chang','ch','ช้าง'),
    AlphabetLetter('ซ','so so','s','โซ่'), AlphabetLetter('ญ','yo ying','y','หญิง'),
    AlphabetLetter('ด','do dek','d','เด็ก'), AlphabetLetter('ต','to tao','t','เต่า'),
    AlphabetLetter('ท','tho thahan','th','ทหาร'), AlphabetLetter('น','no nu','n','หนู'),
    AlphabetLetter('บ','bo baimai','b','ใบไม้'), AlphabetLetter('ป','po pla','p','ปลา'),
    AlphabetLetter('พ','pho phan','ph','พาน'), AlphabetLetter('ฟ','fo fan','f','ฟัน'),
    AlphabetLetter('ม','mo ma','m','ม้า'), AlphabetLetter('ย','yo yak','y','ยักษ์'),
    AlphabetLetter('ร','ro ruea','r','เรือ'), AlphabetLetter('ล','lo ling','l','ลิง'),
    AlphabetLetter('ว','wo waen','w','แหวน'), AlphabetLetter('ส','so suea','s','เสือ'),
    AlphabetLetter('ห','ho hip','h','หีบ'), AlphabetLetter('อ','o ang','o/-','อ่าง'),
    AlphabetLetter('ะ','sara a','a kısa','กะ'), AlphabetLetter('า','sara aa','aa','มา'),
    AlphabetLetter('ิ','sara i','i','มิ'), AlphabetLetter('ี','sara ii','ii','มี'),
    AlphabetLetter('ุ','sara u','u','นุ'), AlphabetLetter('ู','sara uu','uu','ดู'),
    AlphabetLetter('เ','sara e','e','เม'), AlphabetLetter('โ','sara o','o','โต'),
    AlphabetLetter('ไ','sara ai','ai','ไป'),
  ];

  static List<AlphabetLetter> forLang(String code) {
    return switch (code) {
      'ar' => ar,
      'ru' => ru,
      'ja' => ja,
      'ko' => ko,
      'el' => el,
      'he' => he,
      'hi' => hi,
      'th' => th,
      _ => const [],
    };
  }

  static bool isRtl(String code) => code == 'ar' || code == 'he';
}
