import 'package:flutter/foundation.dart';
import 'package:flutter_tts/flutter_tts.dart';

enum AlphabetDirection { ltr, rtl }

@immutable
class NuraLetter {
  const NuraLetter({
    required this.character,
    required this.nameTr,
    required this.nameEn,
    required this.sound,
    required this.exampleWord,
    required this.exampleMeaning,
    this.isVowel = false,
  });
  final String character;
  final String nameTr;
  final String nameEn;
  final String sound;
  final String exampleWord;
  final String exampleMeaning;
  final bool isVowel;
}

@immutable
class NuraAlphabet {
  const NuraAlphabet({required this.languageCode, required this.name, required this.direction, required this.letters});
  final String languageCode;
  final String name;
  final AlphabetDirection direction;
  final List<NuraLetter> letters;
}

class AlphabetEngine {
  static final FlutterTts _tts = FlutterTts();

  static Future<void> initTts() async {
    await _tts.setPitch(1.2);
    await _tts.setSpeechRate(0.35);
  }

  static Future<void> speak(String text, String langCode) async {
    final locale = switch (langCode) {
      'ar' => 'ar-SA', 'ru' => 'ru-RU', 'ja' => 'ja-JP', 'ko' => 'ko-KR',
      'el' => 'el-GR', 'he' => 'he-IL', 'hi' => 'hi-IN', 'th' => 'th-TH',
      'zh' => 'zh-CN', 'tr' => 'tr-TR', 'es' => 'es-ES', 'de' => 'de-DE',
      'fr' => 'fr-FR', 'it' => 'it-IT', 'pt' => 'pt-PT', _ => 'en-US',
    };
    await _tts.setLanguage(locale);
    await _tts.speak(text);
  }

  static NuraAlphabet getAlphabet(String langCode) => _alphabets[langCode] ?? _latin(langCode);

  static final Map<String, NuraAlphabet> _alphabets = {
    'ar': _arabic, 'ru': _russian, 'ja': _japanese, 'ko': _korean,
    'el': _greek, 'he': _hebrew, 'hi': _hindi, 'th': _thai,
  };

  static NuraAlphabet _latin(String lang) => NuraAlphabet(
    languageCode: lang, name: 'Latin Alfabesi', direction: AlphabetDirection.ltr,
    letters: const [
      NuraLetter(character: 'A', nameTr: 'A', nameEn: 'A', sound: 'a', exampleWord: 'Apple', exampleMeaning: 'Elma', isVowel: true),
      NuraLetter(character: 'B', nameTr: 'Be', nameEn: 'Bee', sound: 'b', exampleWord: 'Book', exampleMeaning: 'Kitap'),
      NuraLetter(character: 'C', nameTr: 'Ce', nameEn: 'See', sound: 'c/s', exampleWord: 'Cat', exampleMeaning: 'Kedi'),
      NuraLetter(character: 'D', nameTr: 'De', nameEn: 'Dee', sound: 'd', exampleWord: 'Dog', exampleMeaning: 'Köpek'),
      NuraLetter(character: 'E', nameTr: 'E', nameEn: 'Ee', sound: 'e', exampleWord: 'Egg', exampleMeaning: 'Yumurta', isVowel: true),
      NuraLetter(character: 'F', nameTr: 'Fe', nameEn: 'Ef', sound: 'f', exampleWord: 'Fish', exampleMeaning: 'Balık'),
      NuraLetter(character: 'G', nameTr: 'Ge', nameEn: 'Jee', sound: 'g', exampleWord: 'Good', exampleMeaning: 'İyi'),
      NuraLetter(character: 'H', nameTr: 'He', nameEn: 'Aych', sound: 'h', exampleWord: 'Hello', exampleMeaning: 'Merhaba'),
      NuraLetter(character: 'I', nameTr: 'I', nameEn: 'Ay', sound: 'i/ay', exampleWord: 'Ice', exampleMeaning: 'Buz', isVowel: true),
      NuraLetter(character: 'J', nameTr: 'Je', nameEn: 'Jay', sound: 'j', exampleWord: 'Juice', exampleMeaning: 'Meyve suyu'),
      NuraLetter(character: 'K', nameTr: 'Ke', nameEn: 'Kay', sound: 'k', exampleWord: 'Key', exampleMeaning: 'Anahtar'),
      NuraLetter(character: 'L', nameTr: 'Le', nameEn: 'El', sound: 'l', exampleWord: 'Love', exampleMeaning: 'Aşk'),
      NuraLetter(character: 'M', nameTr: 'Me', nameEn: 'Em', sound: 'm', exampleWord: 'Moon', exampleMeaning: 'Ay'),
      NuraLetter(character: 'N', nameTr: 'Ne', nameEn: 'En', sound: 'n', exampleWord: 'Name', exampleMeaning: 'İsim'),
      NuraLetter(character: 'O', nameTr: 'O', nameEn: 'Oh', sound: 'o', exampleWord: 'Open', exampleMeaning: 'Açmak', isVowel: true),
      NuraLetter(character: 'P', nameTr: 'Pe', nameEn: 'Pee', sound: 'p', exampleWord: 'Pen', exampleMeaning: 'Kalem'),
      NuraLetter(character: 'Q', nameTr: 'Qu', nameEn: 'Kyu', sound: 'kv', exampleWord: 'Queen', exampleMeaning: 'Kraliçe'),
      NuraLetter(character: 'R', nameTr: 'Re', nameEn: 'Ar', sound: 'r', exampleWord: 'Rain', exampleMeaning: 'Yağmur'),
      NuraLetter(character: 'S', nameTr: 'Se', nameEn: 'Es', sound: 's', exampleWord: 'Sun', exampleMeaning: 'Güneş'),
      NuraLetter(character: 'T', nameTr: 'Te', nameEn: 'Tee', sound: 't', exampleWord: 'Tree', exampleMeaning: 'Ağaç'),
      NuraLetter(character: 'U', nameTr: 'U', nameEn: 'Yu', sound: 'u/yu', exampleWord: 'Up', exampleMeaning: 'Yukarı', isVowel: true),
      NuraLetter(character: 'V', nameTr: 'Ve', nameEn: 'Vee', sound: 'v', exampleWord: 'Very', exampleMeaning: 'Çok'),
      NuraLetter(character: 'W', nameTr: 'W', nameEn: 'Double-yu', sound: 'w', exampleWord: 'Water', exampleMeaning: 'Su'),
      NuraLetter(character: 'X', nameTr: 'X', nameEn: 'Eks', sound: 'ks', exampleWord: 'Box', exampleMeaning: 'Kutu'),
      NuraLetter(character: 'Y', nameTr: 'Ye', nameEn: 'Way', sound: 'y', exampleWord: 'Yes', exampleMeaning: 'Evet'),
      NuraLetter(character: 'Z', nameTr: 'Ze', nameEn: 'Zee', sound: 'z', exampleWord: 'Zoo', exampleMeaning: 'Hayvanat bahçesi'),
    ],
  );

  static const _arabic = NuraAlphabet(languageCode: 'ar', name: 'Arap Alfabesi', direction: AlphabetDirection.rtl, letters: [
    NuraLetter(character: 'ا', nameTr: 'Elif', nameEn: 'Alif', sound: 'a', exampleWord: 'أرنب', exampleMeaning: 'Tavşan', isVowel: true),
    NuraLetter(character: 'ب', nameTr: 'Be', nameEn: 'Ba', sound: 'b', exampleWord: 'باب', exampleMeaning: 'Kapı'),
    NuraLetter(character: 'ت', nameTr: 'Te', nameEn: 'Ta', sound: 't', exampleWord: 'تمر', exampleMeaning: 'Hurma'),
    NuraLetter(character: 'ث', nameTr: 'Se', nameEn: 'Tha', sound: 'th', exampleWord: 'ثعلب', exampleMeaning: 'Tilki'),
    NuraLetter(character: 'ج', nameTr: 'Cim', nameEn: 'Jim', sound: 'c', exampleWord: 'جمل', exampleMeaning: 'Deve'),
    NuraLetter(character: 'ح', nameTr: 'Ha', nameEn: 'Ha', sound: 'h (derin)', exampleWord: 'حب', exampleMeaning: 'Sevgi'),
    NuraLetter(character: 'خ', nameTr: 'Hı', nameEn: 'Kha', sound: 'kh', exampleWord: 'خبز', exampleMeaning: 'Ekmek'),
    NuraLetter(character: 'د', nameTr: 'Dal', nameEn: 'Dal', sound: 'd', exampleWord: 'دب', exampleMeaning: 'Ayı'),
    NuraLetter(character: 'ذ', nameTr: 'Zel', nameEn: 'Dhal', sound: 'z (peltek)', exampleWord: 'ذهب', exampleMeaning: 'Altın'),
    NuraLetter(character: 'ر', nameTr: 'Ra', nameEn: 'Ra', sound: 'r', exampleWord: 'رمان', exampleMeaning: 'Nar'),
    NuraLetter(character: 'ز', nameTr: 'Ze', nameEn: 'Zay', sound: 'z', exampleWord: 'زهرة', exampleMeaning: 'Çiçek'),
    NuraLetter(character: 'س', nameTr: 'Sin', nameEn: 'Sin', sound: 's', exampleWord: 'سمك', exampleMeaning: 'Balık'),
    NuraLetter(character: 'ش', nameTr: 'Şın', nameEn: 'Shin', sound: 'ş', exampleWord: 'شمس', exampleMeaning: 'Güneş'),
    NuraLetter(character: 'ص', nameTr: 'Sad', nameEn: 'Sad', sound: 's (kalın)', exampleWord: 'صباح', exampleMeaning: 'Sabah'),
    NuraLetter(character: 'ض', nameTr: 'Dad', nameEn: 'Dad', sound: 'd (kalın)', exampleWord: 'ضوء', exampleMeaning: 'Işık'),
    NuraLetter(character: 'ط', nameTr: 'Tı', nameEn: 'Ta', sound: 't (kalın)', exampleWord: 'طبيب', exampleMeaning: 'Doktor'),
    NuraLetter(character: 'ظ', nameTr: 'Zı', nameEn: 'Dha', sound: 'z (kalın)', exampleWord: 'ظهر', exampleMeaning: 'Öğle'),
    NuraLetter(character: 'ع', nameTr: 'Ayn', nameEn: 'Ayn', sound: 'boğaz sıkışması', exampleWord: 'عين', exampleMeaning: 'Göz'),
    NuraLetter(character: 'غ', nameTr: 'Gayn', nameEn: 'Ghayn', sound: 'g (boğaz)', exampleWord: 'غابة', exampleMeaning: 'Orman'),
    NuraLetter(character: 'ف', nameTr: 'Fe', nameEn: 'Fa', sound: 'f', exampleWord: 'فيل', exampleMeaning: 'Fil'),
    NuraLetter(character: 'ق', nameTr: 'Kaf', nameEn: 'Qaf', sound: 'k (derin)', exampleWord: 'قمر', exampleMeaning: 'Ay'),
    NuraLetter(character: 'ك', nameTr: 'Kef', nameEn: 'Kaf', sound: 'k', exampleWord: 'كتاب', exampleMeaning: 'Kitap'),
    NuraLetter(character: 'ل', nameTr: 'Lam', nameEn: 'Lam', sound: 'l', exampleWord: 'ليمون', exampleMeaning: 'Limon'),
    NuraLetter(character: 'م', nameTr: 'Mim', nameEn: 'Mim', sound: 'm', exampleWord: 'ماء', exampleMeaning: 'Su'),
    NuraLetter(character: 'ن', nameTr: 'Nun', nameEn: 'Nun', sound: 'n', exampleWord: 'نجمة', exampleMeaning: 'Yıldız'),
    NuraLetter(character: 'ه', nameTr: 'He', nameEn: 'Ha', sound: 'h', exampleWord: 'هدية', exampleMeaning: 'Hediye'),
    NuraLetter(character: 'و', nameTr: 'Vav', nameEn: 'Waw', sound: 'v/u', exampleWord: 'ورد', exampleMeaning: 'Gül', isVowel: true),
    NuraLetter(character: 'ي', nameTr: 'Ye', nameEn: 'Ya', sound: 'y/i', exampleWord: 'يد', exampleMeaning: 'El', isVowel: true),
  ]);

  static const _russian = NuraAlphabet(languageCode: 'ru', name: 'Kiril Alfabesi', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'А', nameTr: 'A', nameEn: 'A', sound: 'a', exampleWord: 'Автобус', exampleMeaning: 'Otobüs', isVowel: true),
    NuraLetter(character: 'Б', nameTr: 'Be', nameEn: 'Be', sound: 'b', exampleWord: 'Банан', exampleMeaning: 'Muz'),
    NuraLetter(character: 'В', nameTr: 'Ve', nameEn: 'Ve', sound: 'v', exampleWord: 'Вода', exampleMeaning: 'Su'),
    NuraLetter(character: 'Г', nameTr: 'Ge', nameEn: 'Ge', sound: 'g', exampleWord: 'Город', exampleMeaning: 'Şehir'),
    NuraLetter(character: 'Д', nameTr: 'De', nameEn: 'De', sound: 'd', exampleWord: 'Дом', exampleMeaning: 'Ev'),
    NuraLetter(character: 'Е', nameTr: 'Ye', nameEn: 'Ye', sound: 'ye', exampleWord: 'Еда', exampleMeaning: 'Yemek', isVowel: true),
    NuraLetter(character: 'Ё', nameTr: 'Yo', nameEn: 'Yo', sound: 'yo', exampleWord: 'Ёлка', exampleMeaning: 'Noel ağacı', isVowel: true),
    NuraLetter(character: 'Ж', nameTr: 'Je', nameEn: 'Zhe', sound: 'j', exampleWord: 'Жизнь', exampleMeaning: 'Hayat'),
    NuraLetter(character: 'З', nameTr: 'Ze', nameEn: 'Ze', sound: 'z', exampleWord: 'Звезда', exampleMeaning: 'Yıldız'),
    NuraLetter(character: 'И', nameTr: 'İ', nameEn: 'Ee', sound: 'i', exampleWord: 'Игра', exampleMeaning: 'Oyun', isVowel: true),
    NuraLetter(character: 'Й', nameTr: 'İ kratkoye', nameEn: 'Short I', sound: 'y', exampleWord: 'Йогурт', exampleMeaning: 'Yoğurt'),
    NuraLetter(character: 'К', nameTr: 'Ka', nameEn: 'Ka', sound: 'k', exampleWord: 'Кот', exampleMeaning: 'Kedi'),
    NuraLetter(character: 'Л', nameTr: 'El', nameEn: 'El', sound: 'l', exampleWord: 'Лампа', exampleMeaning: 'Lamba'),
    NuraLetter(character: 'М', nameTr: 'Em', nameEn: 'Em', sound: 'm', exampleWord: 'Мама', exampleMeaning: 'Anne'),
    NuraLetter(character: 'Н', nameTr: 'En', nameEn: 'En', sound: 'n', exampleWord: 'Нос', exampleMeaning: 'Burun'),
    NuraLetter(character: 'О', nameTr: 'O', nameEn: 'O', sound: 'o', exampleWord: 'Окно', exampleMeaning: 'Pencere', isVowel: true),
    NuraLetter(character: 'П', nameTr: 'Pe', nameEn: 'Pe', sound: 'p', exampleWord: 'Парк', exampleMeaning: 'Park'),
    NuraLetter(character: 'Р', nameTr: 'Er', nameEn: 'Er', sound: 'r', exampleWord: 'Рука', exampleMeaning: 'El'),
    NuraLetter(character: 'С', nameTr: 'Es', nameEn: 'Es', sound: 's', exampleWord: 'Сок', exampleMeaning: 'Meyve suyu'),
    NuraLetter(character: 'Т', nameTr: 'Te', nameEn: 'Te', sound: 't', exampleWord: 'Торт', exampleMeaning: 'Pasta'),
    NuraLetter(character: 'У', nameTr: 'U', nameEn: 'U', sound: 'u', exampleWord: 'Ухо', exampleMeaning: 'Kulak', isVowel: true),
    NuraLetter(character: 'Ф', nameTr: 'Ef', nameEn: 'Ef', sound: 'f', exampleWord: 'Фрукт', exampleMeaning: 'Meyve'),
    NuraLetter(character: 'Х', nameTr: 'Ha', nameEn: 'Kha', sound: 'kh', exampleWord: 'Хлеб', exampleMeaning: 'Ekmek'),
    NuraLetter(character: 'Ц', nameTr: 'Tse', nameEn: 'Tse', sound: 'ts', exampleWord: 'Цветок', exampleMeaning: 'Çiçek'),
    NuraLetter(character: 'Ч', nameTr: 'Çe', nameEn: 'Che', sound: 'ch', exampleWord: 'Чай', exampleMeaning: 'Çay'),
    NuraLetter(character: 'Ш', nameTr: 'Şa', nameEn: 'Sha', sound: 'sh', exampleWord: 'Школа', exampleMeaning: 'Okul'),
    NuraLetter(character: 'Щ', nameTr: 'Şça', nameEn: 'Shcha', sound: 'shch', exampleWord: 'Щука', exampleMeaning: 'Turna balığı'),
    NuraLetter(character: 'Ъ', nameTr: 'Sert işaret', nameEn: 'Hard sign', sound: 'sessiz', exampleWord: 'объект', exampleMeaning: 'Nesne'),
    NuraLetter(character: 'Ы', nameTr: 'Yı', nameEn: 'Yeru', sound: 'ı kalın', exampleWord: 'Мышь', exampleMeaning: 'Fare', isVowel: true),
    NuraLetter(character: 'Ь', nameTr: 'Yumuşak işaret', nameEn: 'Soft sign', sound: 'yumuşatır', exampleWord: 'конь', exampleMeaning: 'At'),
    NuraLetter(character: 'Э', nameTr: 'E', nameEn: 'E', sound: 'e', exampleWord: 'Это', exampleMeaning: 'Bu', isVowel: true),
    NuraLetter(character: 'Ю', nameTr: 'Yu', nameEn: 'Yu', sound: 'yu', exampleWord: 'Юг', exampleMeaning: 'Güney', isVowel: true),
    NuraLetter(character: 'Я', nameTr: 'Ya', nameEn: 'Ya', sound: 'ya', exampleWord: 'Яблоко', exampleMeaning: 'Elma', isVowel: true),
  ]);

  static const _japanese = NuraAlphabet(languageCode: 'ja', name: 'Hiragana', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'あ', nameTr: 'A', nameEn: 'A', sound: 'a', exampleWord: 'あめ', exampleMeaning: 'Yağmur', isVowel: true),
    NuraLetter(character: 'い', nameTr: 'İ', nameEn: 'I', sound: 'i', exampleWord: 'いぬ', exampleMeaning: 'Köpek', isVowel: true),
    NuraLetter(character: 'う', nameTr: 'U', nameEn: 'U', sound: 'u', exampleWord: 'うみ', exampleMeaning: 'Deniz', isVowel: true),
    NuraLetter(character: 'え', nameTr: 'E', nameEn: 'E', sound: 'e', exampleWord: 'えき', exampleMeaning: 'İstasyon', isVowel: true),
    NuraLetter(character: 'お', nameTr: 'O', nameEn: 'O', sound: 'o', exampleWord: 'おちゃ', exampleMeaning: 'Çay', isVowel: true),
    NuraLetter(character: 'か', nameTr: 'Ka', nameEn: 'Ka', sound: 'ka', exampleWord: 'かさ', exampleMeaning: 'Şemsiye'),
    NuraLetter(character: 'き', nameTr: 'Ki', nameEn: 'Ki', sound: 'ki', exampleWord: 'きく', exampleMeaning: 'Dinlemek'),
    NuraLetter(character: 'く', nameTr: 'Ku', nameEn: 'Ku', sound: 'ku', exampleWord: 'くも', exampleMeaning: 'Bulut'),
    NuraLetter(character: 'け', nameTr: 'Ke', nameEn: 'Ke', sound: 'ke', exampleWord: 'けさ', exampleMeaning: 'Bu sabah'),
    NuraLetter(character: 'こ', nameTr: 'Ko', nameEn: 'Ko', sound: 'ko', exampleWord: 'こえ', exampleMeaning: 'Ses'),
    NuraLetter(character: 'さ', nameTr: 'Sa', nameEn: 'Sa', sound: 'sa', exampleWord: 'さくら', exampleMeaning: 'Kiraz çiçeği'),
    NuraLetter(character: 'し', nameTr: 'Shi', nameEn: 'Shi', sound: 'shi', exampleWord: 'しお', exampleMeaning: 'Tuz'),
    NuraLetter(character: 'す', nameTr: 'Su', nameEn: 'Su', sound: 'su', exampleWord: 'すし', exampleMeaning: 'Suşi'),
    NuraLetter(character: 'せ', nameTr: 'Se', nameEn: 'Se', sound: 'se', exampleWord: 'せんせい', exampleMeaning: 'Öğretmen'),
    NuraLetter(character: 'そ', nameTr: 'So', nameEn: 'So', sound: 'so', exampleWord: 'そら', exampleMeaning: 'Gökyüzü'),
    NuraLetter(character: 'た', nameTr: 'Ta', nameEn: 'Ta', sound: 'ta', exampleWord: 'たまご', exampleMeaning: 'Yumurta'),
    NuraLetter(character: 'ち', nameTr: 'Chi', nameEn: 'Chi', sound: 'chi', exampleWord: 'ちず', exampleMeaning: 'Harita'),
    NuraLetter(character: 'つ', nameTr: 'Tsu', nameEn: 'Tsu', sound: 'tsu', exampleWord: 'つき', exampleMeaning: 'Ay'),
    NuraLetter(character: 'て', nameTr: 'Te', nameEn: 'Te', sound: 'te', exampleWord: 'てがみ', exampleMeaning: 'Mektup'),
    NuraLetter(character: 'と', nameTr: 'To', nameEn: 'To', sound: 'to', exampleWord: 'とり', exampleMeaning: 'Kuş'),
    NuraLetter(character: 'な', nameTr: 'Na', nameEn: 'Na', sound: 'na', exampleWord: 'なつ', exampleMeaning: 'Yaz'),
    NuraLetter(character: 'に', nameTr: 'Ni', nameEn: 'Ni', sound: 'ni', exampleWord: 'にほん', exampleMeaning: 'Japonya'),
    NuraLetter(character: 'ぬ', nameTr: 'Nu', nameEn: 'Nu', sound: 'nu', exampleWord: 'ぬの', exampleMeaning: 'Kumaş'),
    NuraLetter(character: 'ね', nameTr: 'Ne', nameEn: 'Ne', sound: 'ne', exampleWord: 'ねこ', exampleMeaning: 'Kedi'),
    NuraLetter(character: 'の', nameTr: 'No', nameEn: 'No', sound: 'no', exampleWord: 'のみもの', exampleMeaning: 'İçecek'),
    NuraLetter(character: 'は', nameTr: 'Ha', nameEn: 'Ha', sound: 'ha', exampleWord: 'はな', exampleMeaning: 'Çiçek'),
    NuraLetter(character: 'ひ', nameTr: 'Hi', nameEn: 'Hi', sound: 'hi', exampleWord: 'ひと', exampleMeaning: 'İnsan'),
    NuraLetter(character: 'ふ', nameTr: 'Fu', nameEn: 'Fu', sound: 'fu', exampleWord: 'ふゆ', exampleMeaning: 'Kış'),
    NuraLetter(character: 'へ', nameTr: 'He', nameEn: 'He', sound: 'he', exampleWord: 'へや', exampleMeaning: 'Oda'),
    NuraLetter(character: 'ほ', nameTr: 'Ho', nameEn: 'Ho', sound: 'ho', exampleWord: 'ほん', exampleMeaning: 'Kitap'),
    NuraLetter(character: 'ま', nameTr: 'Ma', nameEn: 'Ma', sound: 'ma', exampleWord: 'まど', exampleMeaning: 'Pencere'),
    NuraLetter(character: 'み', nameTr: 'Mi', nameEn: 'Mi', sound: 'mi', exampleWord: 'みず', exampleMeaning: 'Su'),
    NuraLetter(character: 'む', nameTr: 'Mu', nameEn: 'Mu', sound: 'mu', exampleWord: 'むし', exampleMeaning: 'Böcek'),
    NuraLetter(character: 'め', nameTr: 'Me', nameEn: 'Me', sound: 'me', exampleWord: 'め', exampleMeaning: 'Göz'),
    NuraLetter(character: 'も', nameTr: 'Mo', nameEn: 'Mo', sound: 'mo', exampleWord: 'もも', exampleMeaning: 'Şeftali'),
    NuraLetter(character: 'や', nameTr: 'Ya', nameEn: 'Ya', sound: 'ya', exampleWord: 'やま', exampleMeaning: 'Dağ'),
    NuraLetter(character: 'ゆ', nameTr: 'Yu', nameEn: 'Yu', sound: 'yu', exampleWord: 'ゆき', exampleMeaning: 'Kar'),
    NuraLetter(character: 'よ', nameTr: 'Yo', nameEn: 'Yo', sound: 'yo', exampleWord: 'よる', exampleMeaning: 'Gece'),
    NuraLetter(character: 'ら', nameTr: 'Ra', nameEn: 'Ra', sound: 'ra', exampleWord: 'らいねん', exampleMeaning: 'Gelecek yıl'),
    NuraLetter(character: 'り', nameTr: 'Ri', nameEn: 'Ri', sound: 'ri', exampleWord: 'りんご', exampleMeaning: 'Elma'),
    NuraLetter(character: 'る', nameTr: 'Ru', nameEn: 'Ru', sound: 'ru', exampleWord: 'るす', exampleMeaning: 'Evde yokluk'),
    NuraLetter(character: 'れ', nameTr: 'Re', nameEn: 'Re', sound: 're', exampleWord: 'れいぞうこ', exampleMeaning: 'Buzdolabı'),
    NuraLetter(character: 'ろ', nameTr: 'Ro', nameEn: 'Ro', sound: 'ro', exampleWord: 'ろく', exampleMeaning: 'Altı'),
    NuraLetter(character: 'わ', nameTr: 'Wa', nameEn: 'Wa', sound: 'wa', exampleWord: 'わたし', exampleMeaning: 'Ben'),
    NuraLetter(character: 'を', nameTr: 'Wo', nameEn: 'Wo', sound: 'o', exampleWord: 'を', exampleMeaning: 'Nesne parçacığı'),
    NuraLetter(character: 'ん', nameTr: 'N', nameEn: 'N', sound: 'n', exampleWord: 'にほん', exampleMeaning: 'Japonya'),
  ]);

  static const _korean = NuraAlphabet(languageCode: 'ko', name: 'Hangul', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'ㄱ', nameTr: 'Giyeok', nameEn: 'Giyeok', sound: 'g/k', exampleWord: '가방', exampleMeaning: 'Çanta'),
    NuraLetter(character: 'ㄴ', nameTr: 'Nieun', nameEn: 'Nieun', sound: 'n', exampleWord: '나라', exampleMeaning: 'Ülke'),
    NuraLetter(character: 'ㄷ', nameTr: 'Digeut', nameEn: 'Digeut', sound: 'd/t', exampleWord: '다리', exampleMeaning: 'Köprü'),
    NuraLetter(character: 'ㄹ', nameTr: 'Rieul', nameEn: 'Rieul', sound: 'r/l', exampleWord: '라면', exampleMeaning: 'Ramen'),
    NuraLetter(character: 'ㅁ', nameTr: 'Mieum', nameEn: 'Mieum', sound: 'm', exampleWord: '마을', exampleMeaning: 'Köy'),
    NuraLetter(character: 'ㅂ', nameTr: 'Bieup', nameEn: 'Bieup', sound: 'b/p', exampleWord: '바다', exampleMeaning: 'Deniz'),
    NuraLetter(character: 'ㅅ', nameTr: 'Siot', nameEn: 'Siot', sound: 's', exampleWord: '사람', exampleMeaning: 'İnsan'),
    NuraLetter(character: 'ㅇ', nameTr: 'Ieung', nameEn: 'Ieung', sound: 'ng/-', exampleWord: '아이', exampleMeaning: 'Çocuk'),
    NuraLetter(character: 'ㅈ', nameTr: 'Jieut', nameEn: 'Jieut', sound: 'j', exampleWord: '자전거', exampleMeaning: 'Bisiklet'),
    NuraLetter(character: 'ㅊ', nameTr: 'Chieut', nameEn: 'Chieut', sound: 'ch', exampleWord: '차', exampleMeaning: 'Araba'),
    NuraLetter(character: 'ㅋ', nameTr: 'Kieuk', nameEn: 'Kieuk', sound: 'k', exampleWord: '코', exampleMeaning: 'Burun'),
    NuraLetter(character: 'ㅌ', nameTr: 'Tieut', nameEn: 'Tieut', sound: 't', exampleWord: '타다', exampleMeaning: 'Binmek'),
    NuraLetter(character: 'ㅍ', nameTr: 'Pieup', nameEn: 'Pieup', sound: 'p', exampleWord: '파', exampleMeaning: 'Yeşil soğan'),
    NuraLetter(character: 'ㅎ', nameTr: 'Hieut', nameEn: 'Hieut', sound: 'h', exampleWord: '하나', exampleMeaning: 'Bir'),
    NuraLetter(character: 'ㅏ', nameTr: 'A', nameEn: 'A', sound: 'a', exampleWord: '아기', exampleMeaning: 'Bebek', isVowel: true),
    NuraLetter(character: 'ㅑ', nameTr: 'Ya', nameEn: 'Ya', sound: 'ya', exampleWord: '야구', exampleMeaning: 'Beyzbol', isVowel: true),
    NuraLetter(character: 'ㅓ', nameTr: 'Eo', nameEn: 'Eo', sound: 'eo', exampleWord: '어머니', exampleMeaning: 'Anne', isVowel: true),
    NuraLetter(character: 'ㅕ', nameTr: 'Yeo', nameEn: 'Yeo', sound: 'yeo', exampleWord: '여자', exampleMeaning: 'Kadın', isVowel: true),
    NuraLetter(character: 'ㅗ', nameTr: 'O', nameEn: 'O', sound: 'o', exampleWord: '오리', exampleMeaning: 'Ördek', isVowel: true),
    NuraLetter(character: 'ㅛ', nameTr: 'Yo', nameEn: 'Yo', sound: 'yo', exampleWord: '요리', exampleMeaning: 'Yemek', isVowel: true),
    NuraLetter(character: 'ㅜ', nameTr: 'U', nameEn: 'U', sound: 'u', exampleWord: '우유', exampleMeaning: 'Süt', isVowel: true),
    NuraLetter(character: 'ㅠ', nameTr: 'Yu', nameEn: 'Yu', sound: 'yu', exampleWord: '유리', exampleMeaning: 'Cam', isVowel: true),
    NuraLetter(character: 'ㅡ', nameTr: 'Eu', nameEn: 'Eu', sound: 'eu', exampleWord: '음식', exampleMeaning: 'Yiyecek', isVowel: true),
    NuraLetter(character: 'ㅣ', nameTr: 'I', nameEn: 'I', sound: 'i', exampleWord: '이름', exampleMeaning: 'İsim', isVowel: true),
    NuraLetter(character: 'ㅐ', nameTr: 'Ae', nameEn: 'Ae', sound: 'ae', exampleWord: '애', exampleMeaning: 'Çocuk', isVowel: true),
    NuraLetter(character: 'ㅒ', nameTr: 'Yae', nameEn: 'Yae', sound: 'yae', exampleWord: '얘', exampleMeaning: 'Bu çocuk', isVowel: true),
    NuraLetter(character: 'ㅔ', nameTr: 'E', nameEn: 'E', sound: 'e', exampleWord: '네', exampleMeaning: 'Evet', isVowel: true),
    NuraLetter(character: 'ㅖ', nameTr: 'Ye', nameEn: 'Ye', sound: 'ye', exampleWord: '예', exampleMeaning: 'Evet (nazik)', isVowel: true),
    NuraLetter(character: 'ㅘ', nameTr: 'Wa', nameEn: 'Wa', sound: 'wa', exampleWord: '와', exampleMeaning: 'Ve', isVowel: true),
    NuraLetter(character: 'ㅙ', nameTr: 'Wae', nameEn: 'Wae', sound: 'wae', exampleWord: '왜', exampleMeaning: 'Neden', isVowel: true),
    NuraLetter(character: 'ㅚ', nameTr: 'Oe', nameEn: 'Oe', sound: 'oe', exampleWord: '외', exampleMeaning: 'Dış', isVowel: true),
    NuraLetter(character: 'ㅝ', nameTr: 'Wo', nameEn: 'Wo', sound: 'wo', exampleWord: '워드', exampleMeaning: 'Kelime', isVowel: true),
    NuraLetter(character: 'ㅞ', nameTr: 'We', nameEn: 'We', sound: 'we', exampleWord: '웨이터', exampleMeaning: 'Garson', isVowel: true),
    NuraLetter(character: 'ㅟ', nameTr: 'Wi', nameEn: 'Wi', sound: 'wi', exampleWord: '위', exampleMeaning: 'Üst', isVowel: true),
    NuraLetter(character: 'ㅢ', nameTr: 'Ui', nameEn: 'Ui', sound: 'ui', exampleWord: '의미', exampleMeaning: 'Anlam', isVowel: true),
    NuraLetter(character: 'ㄲ', nameTr: 'Ssang giyeok', nameEn: 'Ssang giyeok', sound: 'kk', exampleWord: '꼬리', exampleMeaning: 'Kuyruk'),
    NuraLetter(character: 'ㄸ', nameTr: 'Ssang digeut', nameEn: 'Ssang digeut', sound: 'tt', exampleWord: '땅', exampleMeaning: 'Toprak'),
    NuraLetter(character: 'ㅃ', nameTr: 'Ssang bieup', nameEn: 'Ssang bieup', sound: 'pp', exampleWord: '빵', exampleMeaning: 'Ekmek'),
    NuraLetter(character: 'ㅆ', nameTr: 'Ssang siot', nameEn: 'Ssang siot', sound: 'ss', exampleWord: '쌀', exampleMeaning: 'Pirinç'),
    NuraLetter(character: 'ㅉ', nameTr: 'Ssang jieut', nameEn: 'Ssang jieut', sound: 'jj', exampleWord: '짜다', exampleMeaning: 'Tuzlu'),
  ]);

  static const _greek = NuraAlphabet(languageCode: 'el', name: 'Yunan Alfabesi', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'Α', nameTr: 'Alfa', nameEn: 'Alpha', sound: 'a', exampleWord: 'Αθήνα', exampleMeaning: 'Atina', isVowel: true),
    NuraLetter(character: 'Β', nameTr: 'Vita', nameEn: 'Beta', sound: 'v', exampleWord: 'Βιβλίο', exampleMeaning: 'Kitap'),
    NuraLetter(character: 'Γ', nameTr: 'Gamma', nameEn: 'Gamma', sound: 'g/y', exampleWord: 'Γάλα', exampleMeaning: 'Süt'),
    NuraLetter(character: 'Δ', nameTr: 'Delta', nameEn: 'Delta', sound: 'dh', exampleWord: 'Δρόμος', exampleMeaning: 'Yol'),
    NuraLetter(character: 'Ε', nameTr: 'Epsilon', nameEn: 'Epsilon', sound: 'e', exampleWord: 'Εγώ', exampleMeaning: 'Ben', isVowel: true),
    NuraLetter(character: 'Ζ', nameTr: 'Zita', nameEn: 'Zeta', sound: 'z', exampleWord: 'Ζωή', exampleMeaning: 'Hayat'),
    NuraLetter(character: 'Η', nameTr: 'İta', nameEn: 'Eta', sound: 'i', exampleWord: 'Ήλιος', exampleMeaning: 'Güneş', isVowel: true),
    NuraLetter(character: 'Θ', nameTr: 'Thita', nameEn: 'Theta', sound: 'th', exampleWord: 'Θάλασσα', exampleMeaning: 'Deniz'),
    NuraLetter(character: 'Ι', nameTr: 'İota', nameEn: 'Iota', sound: 'i', exampleWord: 'Ιδέα', exampleMeaning: 'Fikir', isVowel: true),
    NuraLetter(character: 'Κ', nameTr: 'Kappa', nameEn: 'Kappa', sound: 'k', exampleWord: 'Καφές', exampleMeaning: 'Kahve'),
    NuraLetter(character: 'Λ', nameTr: 'Lambda', nameEn: 'Lambda', sound: 'l', exampleWord: 'Λόγος', exampleMeaning: 'Söz'),
    NuraLetter(character: 'Μ', nameTr: 'Mi', nameEn: 'Mu', sound: 'm', exampleWord: 'Μάνα', exampleMeaning: 'Anne'),
    NuraLetter(character: 'Ν', nameTr: 'Ni', nameEn: 'Nu', sound: 'n', exampleWord: 'Νερό', exampleMeaning: 'Su'),
    NuraLetter(character: 'Ξ', nameTr: 'Ksi', nameEn: 'Xi', sound: 'ks', exampleWord: 'Ξένος', exampleMeaning: 'Yabancı'),
    NuraLetter(character: 'Ο', nameTr: 'Omikron', nameEn: 'Omicron', sound: 'o', exampleWord: 'Όνομα', exampleMeaning: 'İsim', isVowel: true),
    NuraLetter(character: 'Π', nameTr: 'Pi', nameEn: 'Pi', sound: 'p', exampleWord: 'Πόλη', exampleMeaning: 'Şehir'),
    NuraLetter(character: 'Ρ', nameTr: 'Ro', nameEn: 'Rho', sound: 'r', exampleWord: 'Ρόδο', exampleMeaning: 'Gül'),
    NuraLetter(character: 'Σ', nameTr: 'Sigma', nameEn: 'Sigma', sound: 's', exampleWord: 'Σπίτι', exampleMeaning: 'Ev'),
    NuraLetter(character: 'Τ', nameTr: 'Taf', nameEn: 'Tau', sound: 't', exampleWord: 'Τραπέζι', exampleMeaning: 'Masa'),
    NuraLetter(character: 'Υ', nameTr: 'İpsilon', nameEn: 'Upsilon', sound: 'i', exampleWord: 'Ύπνος', exampleMeaning: 'Uyku', isVowel: true),
    NuraLetter(character: 'Φ', nameTr: 'Fi', nameEn: 'Phi', sound: 'f', exampleWord: 'Φως', exampleMeaning: 'Işık'),
    NuraLetter(character: 'Χ', nameTr: 'Hi', nameEn: 'Chi', sound: 'h', exampleWord: 'Χέρι', exampleMeaning: 'El'),
    NuraLetter(character: 'Ψ', nameTr: 'Psi', nameEn: 'Psi', sound: 'ps', exampleWord: 'Ψωμί', exampleMeaning: 'Ekmek'),
    NuraLetter(character: 'Ω', nameTr: 'Omega', nameEn: 'Omega', sound: 'o', exampleWord: 'Ώρα', exampleMeaning: 'Saat', isVowel: true),
  ]);

  static const _hebrew = NuraAlphabet(languageCode: 'he', name: 'İbrani Alfabesi', direction: AlphabetDirection.rtl, letters: [
    NuraLetter(character: 'א', nameTr: 'Alef', nameEn: 'Alef', sound: 'sessiz/a', exampleWord: 'אבא', exampleMeaning: 'Baba'),
    NuraLetter(character: 'ב', nameTr: 'Bet', nameEn: 'Bet', sound: 'b/v', exampleWord: 'בית', exampleMeaning: 'Ev'),
    NuraLetter(character: 'ג', nameTr: 'Gimel', nameEn: 'Gimel', sound: 'g', exampleWord: 'גמל', exampleMeaning: 'Deve'),
    NuraLetter(character: 'ד', nameTr: 'Dalet', nameEn: 'Dalet', sound: 'd', exampleWord: 'דג', exampleMeaning: 'Balık'),
    NuraLetter(character: 'ה', nameTr: 'He', nameEn: 'He', sound: 'h', exampleWord: 'הר', exampleMeaning: 'Dağ'),
    NuraLetter(character: 'ו', nameTr: 'Vav', nameEn: 'Vav', sound: 'v/u', exampleWord: 'ורד', exampleMeaning: 'Gül'),
    NuraLetter(character: 'ז', nameTr: 'Zayin', nameEn: 'Zayin', sound: 'z', exampleWord: 'זהב', exampleMeaning: 'Altın'),
    NuraLetter(character: 'ח', nameTr: 'Het', nameEn: 'Het', sound: 'h (derin)', exampleWord: 'חלון', exampleMeaning: 'Pencere'),
    NuraLetter(character: 'ט', nameTr: 'Tet', nameEn: 'Tet', sound: 't', exampleWord: 'טל', exampleMeaning: 'Çiy'),
    NuraLetter(character: 'י', nameTr: 'Yod', nameEn: 'Yod', sound: 'y/i', exampleWord: 'יד', exampleMeaning: 'El'),
    NuraLetter(character: 'כ', nameTr: 'Kaf', nameEn: 'Kaf', sound: 'k/kh', exampleWord: 'כלב', exampleMeaning: 'Köpek'),
    NuraLetter(character: 'ל', nameTr: 'Lamed', nameEn: 'Lamed', sound: 'l', exampleWord: 'לב', exampleMeaning: 'Kalp'),
    NuraLetter(character: 'מ', nameTr: 'Mem', nameEn: 'Mem', sound: 'm', exampleWord: 'מים', exampleMeaning: 'Su'),
    NuraLetter(character: 'נ', nameTr: 'Nun', nameEn: 'Nun', sound: 'n', exampleWord: 'נהר', exampleMeaning: 'Nehir'),
    NuraLetter(character: 'ס', nameTr: 'Samekh', nameEn: 'Samekh', sound: 's', exampleWord: 'סוס', exampleMeaning: 'At'),
    NuraLetter(character: 'ע', nameTr: 'Ayin', nameEn: 'Ayin', sound: 'gırtlak', exampleWord: 'עין', exampleMeaning: 'Göz'),
    NuraLetter(character: 'פ', nameTr: 'Pe', nameEn: 'Pe', sound: 'p/f', exampleWord: 'פה', exampleMeaning: 'Ağız'),
    NuraLetter(character: 'צ', nameTr: 'Tsadi', nameEn: 'Tsadi', sound: 'ts', exampleWord: 'ציפור', exampleMeaning: 'Kuş'),
    NuraLetter(character: 'ק', nameTr: 'Qof', nameEn: 'Qof', sound: 'k', exampleWord: 'קול', exampleMeaning: 'Ses'),
    NuraLetter(character: 'ר', nameTr: 'Reş', nameEn: 'Resh', sound: 'r', exampleWord: 'ראש', exampleMeaning: 'Baş'),
    NuraLetter(character: 'ש', nameTr: 'Şin', nameEn: 'Shin', sound: 'sh/s', exampleWord: 'שמש', exampleMeaning: 'Güneş'),
    NuraLetter(character: 'ת', nameTr: 'Tav', nameEn: 'Tav', sound: 't', exampleWord: 'תודה', exampleMeaning: 'Teşekkürler'),
  ]);

  static const _hindi = NuraAlphabet(languageCode: 'hi', name: 'Devanagari', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'अ', nameTr: 'A', nameEn: 'A', sound: 'a', exampleWord: 'अनार', exampleMeaning: 'Nar', isVowel: true),
    NuraLetter(character: 'आ', nameTr: 'Aa', nameEn: 'Aa', sound: 'aa', exampleWord: 'आम', exampleMeaning: 'Mango', isVowel: true),
    NuraLetter(character: 'इ', nameTr: 'İ', nameEn: 'I', sound: 'i', exampleWord: 'इमली', exampleMeaning: 'Demirhindi', isVowel: true),
    NuraLetter(character: 'ई', nameTr: 'İi', nameEn: 'Ii', sound: 'ii', exampleWord: 'ईख', exampleMeaning: 'Şeker kamışı', isVowel: true),
    NuraLetter(character: 'उ', nameTr: 'U', nameEn: 'U', sound: 'u', exampleWord: 'उल्लू', exampleMeaning: 'Baykuş', isVowel: true),
    NuraLetter(character: 'ऊ', nameTr: 'Uu', nameEn: 'Uu', sound: 'uu', exampleWord: 'ऊन', exampleMeaning: 'Yün', isVowel: true),
    NuraLetter(character: 'ए', nameTr: 'E', nameEn: 'E', sound: 'e', exampleWord: 'एक', exampleMeaning: 'Bir', isVowel: true),
    NuraLetter(character: 'ऐ', nameTr: 'Ai', nameEn: 'Ai', sound: 'ai', exampleWord: 'ऐनक', exampleMeaning: 'Gözlük', isVowel: true),
    NuraLetter(character: 'ओ', nameTr: 'O', nameEn: 'O', sound: 'o', exampleWord: 'ओखली', exampleMeaning: 'Havan', isVowel: true),
    NuraLetter(character: 'औ', nameTr: 'Au', nameEn: 'Au', sound: 'au', exampleWord: 'औरत', exampleMeaning: 'Kadın', isVowel: true),
    NuraLetter(character: 'क', nameTr: 'Ka', nameEn: 'Ka', sound: 'ka', exampleWord: 'कमल', exampleMeaning: 'Nilüfer'),
    NuraLetter(character: 'ख', nameTr: 'Kha', nameEn: 'Kha', sound: 'kha', exampleWord: 'खरगोश', exampleMeaning: 'Tavşan'),
    NuraLetter(character: 'ग', nameTr: 'Ga', nameEn: 'Ga', sound: 'ga', exampleWord: 'गाय', exampleMeaning: 'İnek'),
    NuraLetter(character: 'घ', nameTr: 'Gha', nameEn: 'Gha', sound: 'gha', exampleWord: 'घर', exampleMeaning: 'Ev'),
    NuraLetter(character: 'च', nameTr: 'Ça', nameEn: 'Cha', sound: 'cha', exampleWord: 'चाय', exampleMeaning: 'Çay'),
    NuraLetter(character: 'छ', nameTr: 'Çha', nameEn: 'Chha', sound: 'chha', exampleWord: 'छत', exampleMeaning: 'Çatı'),
    NuraLetter(character: 'ज', nameTr: 'Ca', nameEn: 'Ja', sound: 'ja', exampleWord: 'जल', exampleMeaning: 'Su'),
    NuraLetter(character: 'झ', nameTr: 'Cah', nameEn: 'Jha', sound: 'jha', exampleWord: 'झाड़ू', exampleMeaning: 'Süpürge'),
    NuraLetter(character: 'ट', nameTr: 'Ṭa', nameEn: 'Ta (retroflex)', sound: 't retro', exampleWord: 'टमाटर', exampleMeaning: 'Domates'),
    NuraLetter(character: 'ठ', nameTr: 'Ṭha', nameEn: 'Tha (retroflex)', sound: 'th', exampleWord: 'ठंडा', exampleMeaning: 'Soğuk'),
    NuraLetter(character: 'ड', nameTr: 'Ḍa', nameEn: 'Da (retroflex)', sound: 'd retro', exampleWord: 'डमरू', exampleMeaning: 'Davul'),
    NuraLetter(character: 'ढ', nameTr: 'Ḍha', nameEn: 'Dha (retroflex)', sound: 'dh', exampleWord: 'ढोल', exampleMeaning: 'Davul'),
    NuraLetter(character: 'त', nameTr: 'Ta', nameEn: 'Ta (dental)', sound: 't', exampleWord: 'तल', exampleMeaning: 'Taban'),
    NuraLetter(character: 'थ', nameTr: 'Tha', nameEn: 'Tha (dental)', sound: 'th', exampleWord: 'थाली', exampleMeaning: 'Tepsi'),
    NuraLetter(character: 'द', nameTr: 'Da', nameEn: 'Da (dental)', sound: 'd', exampleWord: 'दूध', exampleMeaning: 'Süt'),
    NuraLetter(character: 'ध', nameTr: 'Dha', nameEn: 'Dha (dental)', sound: 'dh', exampleWord: 'धन', exampleMeaning: 'Zenginlik'),
    NuraLetter(character: 'न', nameTr: 'Na', nameEn: 'Na', sound: 'n', exampleWord: 'नल', exampleMeaning: 'Musluk'),
    NuraLetter(character: 'प', nameTr: 'Pa', nameEn: 'Pa', sound: 'p', exampleWord: 'पानी', exampleMeaning: 'Su'),
    NuraLetter(character: 'फ', nameTr: 'Pha', nameEn: 'Pha', sound: 'ph', exampleWord: 'फल', exampleMeaning: 'Meyve'),
    NuraLetter(character: 'ब', nameTr: 'Ba', nameEn: 'Ba', sound: 'b', exampleWord: 'बकरी', exampleMeaning: 'Keçi'),
    NuraLetter(character: 'भ', nameTr: 'Bha', nameEn: 'Bha', sound: 'bh', exampleWord: 'भारत', exampleMeaning: 'Hindistan'),
    NuraLetter(character: 'म', nameTr: 'Ma', nameEn: 'Ma', sound: 'm', exampleWord: 'माता', exampleMeaning: 'Anne'),
    NuraLetter(character: 'य', nameTr: 'Ya', nameEn: 'Ya', sound: 'y', exampleWord: 'योग', exampleMeaning: 'Yoga'),
    NuraLetter(character: 'र', nameTr: 'Ra', nameEn: 'Ra', sound: 'r', exampleWord: 'रात', exampleMeaning: 'Gece'),
    NuraLetter(character: 'ल', nameTr: 'La', nameEn: 'La', sound: 'l', exampleWord: 'लड़का', exampleMeaning: 'Erkek çocuk'),
    NuraLetter(character: 'व', nameTr: 'Va', nameEn: 'Va', sound: 'v', exampleWord: 'वन', exampleMeaning: 'Orman'),
    NuraLetter(character: 'श', nameTr: 'Şa', nameEn: 'Sha', sound: 'sh', exampleWord: 'शहर', exampleMeaning: 'Şehir'),
    NuraLetter(character: 'ष', nameTr: 'Şa (kalın)', nameEn: 'Sha (retroflex)', sound: 'sh', exampleWord: 'षट्कोण', exampleMeaning: 'Altıgen'),
    NuraLetter(character: 'स', nameTr: 'Sa', nameEn: 'Sa', sound: 's', exampleWord: 'सब', exampleMeaning: 'Hepsi'),
    NuraLetter(character: 'ह', nameTr: 'Ha', nameEn: 'Ha', sound: 'h', exampleWord: 'हाथ', exampleMeaning: 'El'),
  ]);

  static const _thai = NuraAlphabet(languageCode: 'th', name: 'Tay Alfabesi', direction: AlphabetDirection.ltr, letters: [
    NuraLetter(character: 'ก', nameTr: 'Ko Kai', nameEn: 'Ko Kai', sound: 'k', exampleWord: 'ไก่', exampleMeaning: 'Tavuk'),
    NuraLetter(character: 'ข', nameTr: 'Kho Khai', nameEn: 'Kho Khai', sound: 'kh', exampleWord: 'ไข่', exampleMeaning: 'Yumurta'),
    NuraLetter(character: 'ค', nameTr: 'Kho Khwai', nameEn: 'Kho Khwai', sound: 'kh', exampleWord: 'ควาย', exampleMeaning: 'Bufalo'),
    NuraLetter(character: 'ง', nameTr: 'Ngo Ngu', nameEn: 'Ngo Ngu', sound: 'ng', exampleWord: 'งู', exampleMeaning: 'Yılan'),
    NuraLetter(character: 'จ', nameTr: 'Cho Chan', nameEn: 'Cho Chan', sound: 'j', exampleWord: 'จาน', exampleMeaning: 'Tabak'),
    NuraLetter(character: 'ช', nameTr: 'Cho Chang', nameEn: 'Cho Chang', sound: 'ch', exampleWord: 'ช้าง', exampleMeaning: 'Fil'),
    NuraLetter(character: 'ซ', nameTr: 'So So', nameEn: 'So So', sound: 's', exampleWord: 'โซ่', exampleMeaning: 'Zincir'),
    NuraLetter(character: 'ญ', nameTr: 'Yo Ying', nameEn: 'Yo Ying', sound: 'y', exampleWord: 'หญิง', exampleMeaning: 'Kadın'),
    NuraLetter(character: 'ด', nameTr: 'Do Dek', nameEn: 'Do Dek', sound: 'd', exampleWord: 'เด็ก', exampleMeaning: 'Çocuk'),
    NuraLetter(character: 'ต', nameTr: 'To Tao', nameEn: 'To Tao', sound: 't', exampleWord: 'เต่า', exampleMeaning: 'Kaplumbağa'),
    NuraLetter(character: 'ท', nameTr: 'Tho Thahan', nameEn: 'Tho Thahan', sound: 'th', exampleWord: 'ทหาร', exampleMeaning: 'Asker'),
    NuraLetter(character: 'น', nameTr: 'No Nu', nameEn: 'No Nu', sound: 'n', exampleWord: 'หนู', exampleMeaning: 'Fare'),
    NuraLetter(character: 'บ', nameTr: 'Bo Baimai', nameEn: 'Bo Baimai', sound: 'b', exampleWord: 'ใบไม้', exampleMeaning: 'Yaprak'),
    NuraLetter(character: 'ป', nameTr: 'Po Pla', nameEn: 'Po Pla', sound: 'p', exampleWord: 'ปลา', exampleMeaning: 'Balık'),
    NuraLetter(character: 'พ', nameTr: 'Pho Phan', nameEn: 'Pho Phan', sound: 'ph', exampleWord: 'พาน', exampleMeaning: 'Tepsi'),
    NuraLetter(character: 'ฟ', nameTr: 'Fo Fan', nameEn: 'Fo Fan', sound: 'f', exampleWord: 'ฟัน', exampleMeaning: 'Diş'),
    NuraLetter(character: 'ม', nameTr: 'Mo Ma', nameEn: 'Mo Ma', sound: 'm', exampleWord: 'ม้า', exampleMeaning: 'At'),
    NuraLetter(character: 'ย', nameTr: 'Yo Yak', nameEn: 'Yo Yak', sound: 'y', exampleWord: 'ยักษ์', exampleMeaning: 'Dev'),
    NuraLetter(character: 'ร', nameTr: 'Ro Ruea', nameEn: 'Ro Ruea', sound: 'r', exampleWord: 'เรือ', exampleMeaning: 'Tekne'),
    NuraLetter(character: 'ล', nameTr: 'Lo Ling', nameEn: 'Lo Ling', sound: 'l', exampleWord: 'ลิง', exampleMeaning: 'Maymun'),
    NuraLetter(character: 'ว', nameTr: 'Wo Waen', nameEn: 'Wo Waen', sound: 'w', exampleWord: 'แหวน', exampleMeaning: 'Yüzük'),
    NuraLetter(character: 'ส', nameTr: 'So Suea', nameEn: 'So Suea', sound: 's', exampleWord: 'เสือ', exampleMeaning: 'Kaplan'),
    NuraLetter(character: 'ห', nameTr: 'Ho Hip', nameEn: 'Ho Hip', sound: 'h', exampleWord: 'หีบ', exampleMeaning: 'Sandık'),
    NuraLetter(character: 'อ', nameTr: 'O Ang', nameEn: 'O Ang', sound: 'o/-', exampleWord: 'อ่าง', exampleMeaning: 'Leğen'),
    NuraLetter(character: 'ะ', nameTr: 'Sara A', nameEn: 'Sara A', sound: 'a kısa', exampleWord: 'กะ', exampleMeaning: 'Kısa a'),
    NuraLetter(character: 'า', nameTr: 'Sara Aa', nameEn: 'Sara Aa', sound: 'aa', exampleWord: 'มา', exampleMeaning: 'Gelmek'),
    NuraLetter(character: 'ิ', nameTr: 'Sara İ', nameEn: 'Sara I', sound: 'i', exampleWord: 'มิ', exampleMeaning: 'İ işareti'),
    NuraLetter(character: 'ี', nameTr: 'Sara İi', nameEn: 'Sara Ii', sound: 'ii', exampleWord: 'มี', exampleMeaning: 'Sahip olmak'),
    NuraLetter(character: 'ุ', nameTr: 'Sara U', nameEn: 'Sara U', sound: 'u', exampleWord: 'นุ', exampleMeaning: 'U işareti'),
    NuraLetter(character: 'ู', nameTr: 'Sara Uu', nameEn: 'Sara Uu', sound: 'uu', exampleWord: 'ดู', exampleMeaning: 'Bakmak'),
    NuraLetter(character: 'เ', nameTr: 'Sara E', nameEn: 'Sara E', sound: 'e', exampleWord: 'เม', exampleMeaning: 'E işareti'),
    NuraLetter(character: 'โ', nameTr: 'Sara O', nameEn: 'Sara O', sound: 'o', exampleWord: 'โต', exampleMeaning: 'Büyük'),
    NuraLetter(character: 'ไ', nameTr: 'Sara Ai', nameEn: 'Sara Ai', sound: 'ai', exampleWord: 'ไป', exampleMeaning: 'Gitmek'),
  ]);
}
