class AlphabetLetter {
  final String char;
  final String name;
  final String soundLike;
  final String example;
  const AlphabetLetter(this.char, this.name, this.soundLike, this.example);
}

class AlphabetData {
  static const ar = <AlphabetLetter>[
    AlphabetLetter('ا', 'Elif', 'a', 'أب'),
    AlphabetLetter('ب', 'Ba', 'b', 'باب'),
    AlphabetLetter('ت', 'Ta', 't', 'تمر'),
    AlphabetLetter('ث', 'Se', 'th', 'ثلج'),
    AlphabetLetter('ج', 'Cim', 'j', 'جمل'),
    AlphabetLetter('ح', 'Ha', 'h derin', 'حب'),
    AlphabetLetter('خ', 'Hı', 'kh', 'خبز'),
    AlphabetLetter('د', 'Dal', 'd', 'دار'),
    AlphabetLetter('ذ', 'Zel', 'dh', 'ذهب'),
    AlphabetLetter('ر', 'Ra', 'r', 'رأس'),
    AlphabetLetter('ز', 'Ze', 'z', 'زيت'),
    AlphabetLetter('س', 'Sin', 's', 'سلام'),
    AlphabetLetter('ش', 'Şın', 'sh', 'شمس'),
    AlphabetLetter('ص', 'Sad', 's kalın', 'صباح'),
    AlphabetLetter('ض', 'Dad', 'd kalın', 'ضوء'),
    AlphabetLetter('ط', 'Tı', 't kalın', 'طبيب'),
    AlphabetLetter('ظ', 'Zı', 'z kalın', 'ظهر'),
    AlphabetLetter('ع', 'Ayn', 'a gırtlak', 'عين'),
    AlphabetLetter('غ', 'Ğayn', 'gh', 'غدا'),
    AlphabetLetter('ف', 'Fe', 'f', 'فم'),
    AlphabetLetter('ق', 'Kaf', 'q', 'قلب'),
    AlphabetLetter('ك', 'Kef', 'k', 'كتاب'),
    AlphabetLetter('ل', 'Lam', 'l', 'ليل'),
    AlphabetLetter('م', 'Mim', 'm', 'ماء'),
    AlphabetLetter('ن', 'Nun', 'n', 'نور'),
    AlphabetLetter('ه', 'He', 'h', 'هذا'),
    AlphabetLetter('و', 'Vav', 'w/u', 'ورد'),
    AlphabetLetter('ي', 'Ye', 'y/i', 'يد'),
  ];

  static const ru = <AlphabetLetter>[
    AlphabetLetter('А', 'A', 'a', 'мама'),
    AlphabetLetter('Б', 'Be', 'b', 'брат'),
    AlphabetLetter('В', 'Ve', 'v', 'вода'),
    AlphabetLetter('Г', 'Ge', 'g', 'город'),
    AlphabetLetter('Д', 'De', 'd', 'дом'),
    AlphabetLetter('Е', 'Ye', 'ye', 'еда'),
    AlphabetLetter('Ё', 'Yo', 'yo', 'ёлка'),
    AlphabetLetter('Ж', 'Je', 'zh', 'жизнь'),
    AlphabetLetter('З', 'Ze', 'z', 'зима'),
    AlphabetLetter('И', 'İ', 'i', 'имя'),
    AlphabetLetter('Й', 'İ kratkoye', 'y', 'чай'),
    AlphabetLetter('К', 'Ka', 'k', 'кофе'),
    AlphabetLetter('Л', 'El', 'l', 'лес'),
    AlphabetLetter('М', 'Em', 'm', 'море'),
    AlphabetLetter('Н', 'En', 'n', 'ночь'),
    AlphabetLetter('О', 'O', 'o', 'окно'),
    AlphabetLetter('П', 'Pe', 'p', 'папа'),
    AlphabetLetter('Р', 'Er', 'r', 'рука'),
    AlphabetLetter('С', 'Es', 's', 'сон'),
    AlphabetLetter('Т', 'Te', 't', 'стол'),
    AlphabetLetter('У', 'U', 'u', 'утро'),
    AlphabetLetter('Ф', 'Ef', 'f', 'фильм'),
    AlphabetLetter('Х', 'Ha', 'kh', 'хлеб'),
    AlphabetLetter('Ц', 'Tse', 'ts', 'цвет'),
    AlphabetLetter('Ч', 'Çe', 'ch', 'чай'),
    AlphabetLetter('Ш', 'Şa', 'sh', 'школа'),
    AlphabetLetter('Щ', 'Şça', 'shch', 'щи'),
    AlphabetLetter('Ъ', 'Sert işaret', 'sessiz', 'объект'),
    AlphabetLetter('Ы', 'I', 'ı kalın', 'сын'),
    AlphabetLetter('Ь', 'Yumuşak işaret', 'yumuşatır', 'день'),
    AlphabetLetter('Э', 'E', 'e', 'это'),
    AlphabetLetter('Ю', 'Yu', 'yu', 'юг'),
    AlphabetLetter('Я', 'Ya', 'ya', 'яблоко'),
  ];

  static const ja = <AlphabetLetter>[
    AlphabetLetter('あ','a','a','あめ'), AlphabetLetter('い','i','i','いぬ'),
    AlphabetLetter('う','u','u','うみ'), AlphabetLetter('え','e','e','えき'),
    AlphabetLetter('お','o','o','おちゃ'), AlphabetLetter('か','ka','ka','かさ'),
    AlphabetLetter('き','ki','ki','き'), AlphabetLetter('く','ku','ku','くつ'),
    AlphabetLetter('け','ke','ke','け'), AlphabetLetter('こ','ko','ko','こども'),
    AlphabetLetter('さ','sa','sa','さかな'), AlphabetLetter('し','shi','shi','しろ'),
    AlphabetLetter('す','su','su','すし'), AlphabetLetter('せ','se','se','せんせい'),
    AlphabetLetter('そ','so','so','そら'), AlphabetLetter('た','ta','ta','たべる'),
    AlphabetLetter('ち','chi','chi','ちず'), AlphabetLetter('つ','tsu','tsu','つき'),
    AlphabetLetter('て','te','te','て'), AlphabetLetter('と','to','to','とり'),
    AlphabetLetter('な','na','na','なまえ'), AlphabetLetter('に','ni','ni','にほん'),
    AlphabetLetter('ぬ','nu','nu','ぬの'), AlphabetLetter('ね','ne','ne','ねこ'),
    AlphabetLetter('の','no','no','のむ'), AlphabetLetter('は','ha','ha','はな'),
    AlphabetLetter('ひ','hi','hi','ひと'), AlphabetLetter('ふ','fu','fu','ふね'),
    AlphabetLetter('へ','he','he','へや'), AlphabetLetter('ほ','ho','ho','ほん'),
    AlphabetLetter('ま','ma','ma','まど'), AlphabetLetter('み','mi','mi','みず'),
    AlphabetLetter('む','mu','mu','むし'), AlphabetLetter('め','me','me','め'),
    AlphabetLetter('も','mo','mo','もも'), AlphabetLetter('や','ya','ya','やま'),
    AlphabetLetter('ゆ','yu','yu','ゆき'), AlphabetLetter('よ','yo','yo','よる'),
    AlphabetLetter('ら','ra','ra','らいねん'), AlphabetLetter('り','ri','ri','りんご'),
    AlphabetLetter('る','ru','ru','るす'), AlphabetLetter('れ','re','re','れいぞうこ'),
    AlphabetLetter('ろ','ro','ro','ろく'), AlphabetLetter('わ','wa','wa','わたし'),
    AlphabetLetter('を','wo','o','を'), AlphabetLetter('ん','n','n','せん'),
  ];

  static const ko = <AlphabetLetter>[
    AlphabetLetter('ㄱ','giyeok','g/k','가방'), AlphabetLetter('ㄴ','nieun','n','나라'),
    AlphabetLetter('ㄷ','digeut','d/t','다리'), AlphabetLetter('ㄹ','rieul','r/l','라면'),
    AlphabetLetter('ㅁ','mieum','m','마음'), AlphabetLetter('ㅂ','bieup','b/p','바다'),
    AlphabetLetter('ㅅ','siot','s','사람'), AlphabetLetter('ㅇ','ieung','ng/-','아이'),
    AlphabetLetter('ㅈ','jieut','j','자전거'), AlphabetLetter('ㅊ','chieut','ch','차'),
    AlphabetLetter('ㅋ','kieuk','k','코'), AlphabetLetter('ㅌ','tieut','t','타다'),
    AlphabetLetter('ㅍ','pieup','p','파'), AlphabetLetter('ㅎ','hieut','h','하나'),
    AlphabetLetter('ㅏ','a','a','아기'), AlphabetLetter('ㅑ','ya','ya','야구'),
    AlphabetLetter('ㅓ','eo','eo','어머니'), AlphabetLetter('ㅕ','yeo','yeo','여자'),
    AlphabetLetter('ㅗ','o','o','오리'), AlphabetLetter('ㅛ','yo','yo','요리'),
    AlphabetLetter('ㅜ','u','u','우유'), AlphabetLetter('ㅠ','yu','yu','유리'),
    AlphabetLetter('ㅡ','eu','eu','음식'), AlphabetLetter('ㅣ','i','i','이름'),
    AlphabetLetter('ㅐ','ae','ae','애'), AlphabetLetter('ㅔ','e','e','네'),
    AlphabetLetter('ㅒ','yae','yae','얘'), AlphabetLetter('ㅖ','ye','ye','예'),
    AlphabetLetter('ㅘ','wa','wa','와'), AlphabetLetter('ㅙ','wae','wae','왜'),
    AlphabetLetter('ㅚ','oe','oe','외'), AlphabetLetter('ㅝ','wo','wo','워'),
    AlphabetLetter('ㅞ','we','we','웨'), AlphabetLetter('ㅟ','wi','wi','위'),
    AlphabetLetter('ㅢ','ui','ui','의'), AlphabetLetter('ㄲ','ssang giyeok','kk','꼬리'),
    AlphabetLetter('ㄸ','ssang digeut','tt','땅'), AlphabetLetter('ㅃ','ssang bieup','pp','빵'),
    AlphabetLetter('ㅆ','ssang siot','ss','쌀'), AlphabetLetter('ㅉ','ssang jieut','jj','짜다'),
  ];

  static const el = <AlphabetLetter>[
    AlphabetLetter('Α','Alfa','a','Αγάπη'), AlphabetLetter('Β','Vita','v','Βιβλίο'),
    AlphabetLetter('Γ','Gamma','gh','Γάλα'), AlphabetLetter('Δ','Delta','dh','Δρόμος'),
    AlphabetLetter('Ε','Epsilon','e','Εγώ'), AlphabetLetter('Ζ','Zita','z','Ζωή'),
    AlphabetLetter('Η','Ita','i','Ήλιος'), AlphabetLetter('Θ','Thita','th','Θάλασσα'),
    AlphabetLetter('Ι','Iota','i','Ιδέα'), AlphabetLetter('Κ','Kappa','k','Καφές'),
    AlphabetLetter('Λ','Lambda','l','Λόγος'), AlphabetLetter('Μ','Mi','m','Μάνα'),
    AlphabetLetter('Ν','Ni','n','Νερό'), AlphabetLetter('Ξ','Ksi','ks','Ξένος'),
    AlphabetLetter('Ο','Omikron','o','Όνομα'), AlphabetLetter('Π','Pi','p','Πόλη'),
    AlphabetLetter('Ρ','Ro','r','Ρόδο'), AlphabetLetter('Σ','Sigma','s','Σπίτι'),
    AlphabetLetter('Τ','Taf','t','Τραπέζι'), AlphabetLetter('Υ','Ipsilon','i','Ύπνος'),
    AlphabetLetter('Φ','Fi','f','Φως'), AlphabetLetter('Χ','Hi','h','Χέρι'),
    AlphabetLetter('Ψ','Psi','ps','Ψωμί'), AlphabetLetter('Ω','Omega','o','Ώρα'),
  ];

  static const he = <AlphabetLetter>[
    AlphabetLetter('א','Alef','sessiz/a','אבא'), AlphabetLetter('ב','Bet','b/v','בית'),
    AlphabetLetter('ג','Gimel','g','גמל'), AlphabetLetter('ד','Dalet','d','דלת'),
    AlphabetLetter('ה','He','h','הר'), AlphabetLetter('ו','Vav','v/u','ורד'),
    AlphabetLetter('ז','Zayin','z','זהב'), AlphabetLetter('ח','Het','h derin','חלון'),
    AlphabetLetter('ט','Tet','t','טל'), AlphabetLetter('י','Yod','y/i','יד'),
    AlphabetLetter('כ','Kaf','k/kh','כלב'), AlphabetLetter('ל','Lamed','l','לב'),
    AlphabetLetter('מ','Mem','m','מים'), AlphabetLetter('נ','Nun','n','נהר'),
    AlphabetLetter('ס','Samekh','s','סוס'), AlphabetLetter('ע','Ayin','gırtlak','עין'),
    AlphabetLetter('פ','Pe','p/f','פה'), AlphabetLetter('צ','Tsadi','ts','צפור'),
    AlphabetLetter('ק','Qof','k','קול'), AlphabetLetter('ר','Resh','r','ראש'),
    AlphabetLetter('ש','Shin','sh/s','שמש'), AlphabetLetter('ת','Tav','t','תודה'),
  ];

  static const hi = <AlphabetLetter>[
    AlphabetLetter('अ','a','a','अनार'), AlphabetLetter('आ','aa','aa','आम'),
    AlphabetLetter('इ','i','i','इमली'), AlphabetLetter('ई','ii','ii','ईख'),
    AlphabetLetter('उ','u','u','उल्लू'), AlphabetLetter('ऊ','uu','uu','ऊन'),
    AlphabetLetter('ए','e','e','एक'), AlphabetLetter('ऐ','ai','ai','ऐनक'),
    AlphabetLetter('ओ','o','o','ओखली'), AlphabetLetter('औ','au','au','औरत'),
    AlphabetLetter('क','ka','k','कम'), AlphabetLetter('ख','kha','kh','खाना'),
    AlphabetLetter('ग','ga','g','घर'), AlphabetLetter('घ','gha','gh','घर'),
    AlphabetLetter('च','cha','ch','चाय'), AlphabetLetter('छ','chha','chh','छत'),
    AlphabetLetter('ज','ja','j','जल'), AlphabetLetter('झ','jha','jh','झाड़ू'),
    AlphabetLetter('ट','ṭa','t retro','टमाटर'), AlphabetLetter('ठ','ṭha','th','ठंडा'),
    AlphabetLetter('ड','ḍa','d retro','डमरू'), AlphabetLetter('ढ','ḍha','dh','ढोल'),
    AlphabetLetter('त','ta','t','तल'), AlphabetLetter('थ','tha','th','थाली'),
    AlphabetLetter('द','da','d','दूध'), AlphabetLetter('ध','dha','dh','धन'),
    AlphabetLetter('न','na','n','नल'), AlphabetLetter('प','pa','p','पानी'),
    AlphabetLetter('फ','pha','ph','फल'), AlphabetLetter('ब','ba','b','बकरी'),
    AlphabetLetter('भ','bha','bh','भारत'), AlphabetLetter('म','ma','m','माता'),
    AlphabetLetter('य','ya','y','योग'), AlphabetLetter('र','ra','r','रात'),
    AlphabetLetter('ल','la','l','लड़का'), AlphabetLetter('व','va','v','वन'),
    AlphabetLetter('श','sha','sh','शहर'), AlphabetLetter('ष','ṣha','sh','षट्कोण'),
    AlphabetLetter('स','sa','s','सब'), AlphabetLetter('ह','ha','h','हाथ'),
  ];

  static const th = <AlphabetLetter>[
    AlphabetLetter('ก','ko kai','k','ไก่'), AlphabetLetter('ข','kho khai','kh','ไข่'),
    AlphabetLetter('ค','kho khwai','kh','ควาย'), AlphabetLetter('ง','ngo ngu','ng','งู'),
    AlphabetLetter('จ','cho chan','j','จาน'), AlphabetLetter('ช','cho chang','ch','ช้าง'),
    AlphabetLetter('ซ','so so','s','โซ่'), AlphabetLetter('ญ','yo ying','y','หญิง'),
    AlphabetLetter('ด','do dek','d','เด็ก'), AlphabetLetter('ต','to tao','t','เต่า'),
    AlphabetLetter('ท','tho thahan','th','ทหาร'), AlphabetLetter('น','no nu','n','หนู'),
    AlphabetLetter('บ','bo baimai','b','ใบไม้'), AlphabetLetter('ป','po pla','p','ปลา'),
    AlphabetLetter('พ','pho phan','ph','พาน'), AlphabetLetter('ฟ','fo fan','f','ฟัน'),
    AlphabetLetter('ม','mo ma','m','ม้า'), AlphabetLetter('ย','yo yak','y','ยักษ์'),
    AlphabetLetter('ร','ro ruea','r','เรือ'), AlphabetLetter('ล','lo ling','l','ลิง'),
    AlphabetLetter('ว','wo waen','w','แหวน'), AlphabetLetter('ส','so suea','s','เสือ'),
    AlphabetLetter('ห','ho hip','h','หีบ'), AlphabetLetter('อ','o ang','o/-','อ่าง'),
    AlphabetLetter('ะ','sara a','a kısa','กะ'), AlphabetLetter('า','sara aa','aa','มา'),
    AlphabetLetter('ิ','sara i','i','มิ'), AlphabetLetter('ี','sara ii','ii','มี'),
    AlphabetLetter('ุ','sara u','u','นุ'), AlphabetLetter('ู','sara uu','uu','ดู'),
    AlphabetLetter('เ','sara e','e','เม'), AlphabetLetter('โ','sara o','o','โต'),
    AlphabetLetter('ไ','sara ai','ai','ไป'),
  ];

  /// Latin alfabesi dilleri için HARF-SES farkı tabloları.
  /// Aynı harf her dilde aynı okunmaz: İngilizce A = "ey", Türkçe A = "a".
  static const en = <AlphabetLetter>[
    AlphabetLetter('A', 'A', 'ey', 'apple (elma)'),
    AlphabetLetter('B', 'Bee', 'bi', 'boy (oğlan)'),
    AlphabetLetter('C', 'Cee', 's / k', 'cat · city'),
    AlphabetLetter('D', 'Dee', 'di', 'dog (köpek)'),
    AlphabetLetter('E', 'Ee', 'i', 'egg (yumurta)'),
    AlphabetLetter('F', 'Ef', 'ef', 'fish (balık)'),
    AlphabetLetter('G', 'Gee', 'g / c', 'go · gem'),
    AlphabetLetter('H', 'Aitch', 'heyç', 'hat (şapka)'),
    AlphabetLetter('I', 'Eye', 'ay', 'ice (buz)'),
    AlphabetLetter('J', 'Jay', 'cey', 'jump (zıpla)'),
    AlphabetLetter('K', 'Kay', 'key', 'kite (uçurtma)'),
    AlphabetLetter('L', 'El', 'el', 'lion (aslan)'),
    AlphabetLetter('M', 'Em', 'em', 'moon (ay)'),
    AlphabetLetter('N', 'En', 'en', 'night (gece)'),
    AlphabetLetter('O', 'Oh', 'o', 'orange (portakal)'),
    AlphabetLetter('P', 'Pee', 'pi', 'pen (kalem)'),
    AlphabetLetter('Q', 'Cue', 'kiu', 'queen (kraliçe)'),
    AlphabetLetter('R', 'Ar', 'ar', 'red (kırmızı)'),
    AlphabetLetter('S', 'Es', 'es', 'sun (güneş)'),
    AlphabetLetter('T', 'Tee', 'ti', 'tree (ağaç)'),
    AlphabetLetter('U', 'You', 'yu', 'umbrella (şemsiye)'),
    AlphabetLetter('V', 'Vee', 'vi', 'van (kamyonet)'),
    AlphabetLetter('W', 'Double-u', 'dabılyu', 'water (su)'),
    AlphabetLetter('X', 'Ex', 'eks', 'box (kutu)'),
    AlphabetLetter('Y', 'Why', 'vay', 'yes (evet)'),
    AlphabetLetter('Z', 'Zed', 'zed', 'zebra (zebra)'),
  ];

  static const es = <AlphabetLetter>[
    AlphabetLetter('A', 'A', 'a', 'agua (su)'),
    AlphabetLetter('B', 'Be', 'be', 'barco (gemi)'),
    AlphabetLetter('C', 'Ce', 's / k', 'casa · cielo'),
    AlphabetLetter('CH', 'Che', 'çe', 'chico (çocuk)'),
    AlphabetLetter('D', 'De', 'de', 'dedo (parmak)'),
    AlphabetLetter('E', 'E', 'e', 'elefante (fil)'),
    AlphabetLetter('F', 'Efe', 'efe', 'fuego (ateş)'),
    AlphabetLetter('G', 'Ge', 'g / h', 'gato · gente'),
    AlphabetLetter('H', 'Hache', 'sessiz', 'hola (merhaba)'),
    AlphabetLetter('I', 'I', 'i', 'isla (ada)'),
    AlphabetLetter('J', 'Jota', 'hota', 'jardín (bahçe)'),
    AlphabetLetter('K', 'Ka', 'ka', 'kilo (kilo)'),
    AlphabetLetter('L', 'Ele', 'ele', 'luna (ay)'),
    AlphabetLetter('LL', 'Elle', 'eye', 'llave (anahtar)'),
    AlphabetLetter('M', 'Eme', 'eme', 'mano (el)'),
    AlphabetLetter('N', 'Ene', 'ene', 'noche (gece)'),
    AlphabetLetter('Ñ', 'Eñe', 'enye', 'niño (çocuk)'),
    AlphabetLetter('O', 'O', 'o', 'ojo (göz)'),
    AlphabetLetter('P', 'Pe', 'pe', 'perro (köpek)'),
    AlphabetLetter('Q', 'Cu', 'ku', 'queso (peynir)'),
    AlphabetLetter('R', 'Ere', 'ere', 'rojo (kırmızı)'),
    AlphabetLetter('S', 'Ese', 'ese', 'sol (güneş)'),
    AlphabetLetter('T', 'Te', 'te', 'taza (fincan)'),
    AlphabetLetter('U', 'U', 'u', 'uva (üzüm)'),
    AlphabetLetter('V', 'Uve', 'uve', 'vaca (inek)'),
    AlphabetLetter('W', 'Uve doble', 'uve doble', 'wifi (wifi)'),
    AlphabetLetter('X', 'Equis', 'ekis', 'taxi (taksi)'),
    AlphabetLetter('Y', 'Ye', 'ye', 'yo (ben)'),
    AlphabetLetter('Z', 'Zeta', 'seta', 'zapato (ayakkabı)'),
  ];

  static const de = <AlphabetLetter>[
    AlphabetLetter('A', 'A', 'a', 'Apfel (elma)'),
    AlphabetLetter('Ä', 'Ä', 'ä', 'Äpfel (elmalar)'),
    AlphabetLetter('B', 'Be', 'be', 'Bett (yatak)'),
    AlphabetLetter('C', 'Ce', 'tse', 'Computer (bilgisayar)'),
    AlphabetLetter('D', 'De', 'de', 'Dach (çatı)'),
    AlphabetLetter('E', 'E', 'e', 'Elefant (fil)'),
    AlphabetLetter('F', 'Ef', 'ef', 'Fisch (balık)'),
    AlphabetLetter('G', 'Ge', 'ge', 'Garten (bahçe)'),
    AlphabetLetter('H', 'Ha', 'ha', 'Haus (ev)'),
    AlphabetLetter('I', 'I', 'i', 'Insel (ada)'),
    AlphabetLetter('J', 'Jot', 'yot', 'Jahr (yıl)'),
    AlphabetLetter('K', 'Ka', 'ka', 'Katze (kedi)'),
    AlphabetLetter('L', 'El', 'el', 'Lampe (lamba)'),
    AlphabetLetter('M', 'Em', 'em', 'Maus (fare)'),
    AlphabetLetter('N', 'En', 'en', 'Nacht (gece)'),
    AlphabetLetter('O', 'O', 'o', 'Obst (meyve)'),
    AlphabetLetter('Ö', 'Ö', 'ö', 'Öl (yağ)'),
    AlphabetLetter('P', 'Pe', 'pe', 'Papier (kağıt)'),
    AlphabetLetter('Q', 'Qu', 'ku', 'Quelle (kaynak)'),
    AlphabetLetter('R', 'Er', 'er', 'Rose (gül)'),
    AlphabetLetter('S', 'Es', 'es', 'Sonne (güneş)'),
    AlphabetLetter('T', 'Te', 'te', 'Tisch (masa)'),
    AlphabetLetter('U', 'U', 'u', 'Uhr (saat)'),
    AlphabetLetter('Ü', 'Ü', 'ü', 'Über (üstünde)'),
    AlphabetLetter('V', 'Vau', 'fau', 'Vogel (kuş)'),
    AlphabetLetter('W', 'We', 've', 'Wasser (su)'),
    AlphabetLetter('X', 'Ix', 'iks', 'Xylophon (ksilofon)'),
    AlphabetLetter('Y', 'Ypsilon', 'üpsilon', 'Physik (fizik)'),
    AlphabetLetter('Z', 'Zett', 'tset', 'Zeit (zaman)'),
    AlphabetLetter('ß', 'Eszett', 'eszett', 'Straße (cadde)'),
  ];

  static const fr = <AlphabetLetter>[
    AlphabetLetter('A', 'A', 'a', 'avion (uçak)'),
    AlphabetLetter('B', 'Bé', 'be', 'bateau (gemi)'),
    AlphabetLetter('C', 'Cé', 's / k', 'chat · ciel'),
    AlphabetLetter('D', 'Dé', 'de', 'dents (dişler)'),
    AlphabetLetter('E', 'E', 'e', 'école (okul)'),
    AlphabetLetter('F', 'Effe', 'ef', 'fleur (çiçek)'),
    AlphabetLetter('G', 'Gé', 'j / g', 'garçon · girafe'),
    AlphabetLetter('H', 'Ache', 'sessiz', 'hôtel (otel)'),
    AlphabetLetter('I', 'I', 'i', 'île (ada)'),
    AlphabetLetter('J', 'Ji', 'ji', 'jardin (bahçe)'),
    AlphabetLetter('K', 'Ka', 'ka', 'kangourou (kanguru)'),
    AlphabetLetter('L', 'El', 'el', 'livre (kitap)'),
    AlphabetLetter('M', 'Em', 'em', 'maison (ev)'),
    AlphabetLetter('N', 'En', 'en', 'nuit (gece)'),
    AlphabetLetter('O', 'O', 'o', 'orange (portakal)'),
    AlphabetLetter('P', 'Pé', 'pe', 'pomme (elma)'),
    AlphabetLetter('Q', 'Ku', 'ku', 'quatre (dört)'),
    AlphabetLetter('R', 'Er', 'er', 'rouge (kırmızı)'),
    AlphabetLetter('S', 'Es', 'es', 'soleil (güneş)'),
    AlphabetLetter('T', 'Té', 'te', 'table (masa)'),
    AlphabetLetter('U', 'U', 'ü', 'usine (fabrika)'),
    AlphabetLetter('V', 'Vé', 've', 'vélo (bisiklet)'),
    AlphabetLetter('W', 'Double vé', 'dubl ve', 'wagon (vagon)'),
    AlphabetLetter('X', 'Ix', 'iks', 'taxi (taksi)'),
    AlphabetLetter('Y', 'Y grec', 'i grek', 'yeux (gözler)'),
    AlphabetLetter('Z', 'Zède', 'zed', 'zèbre (zebra)'),
    AlphabetLetter('Ç', 'Cé cédille', 'se sedilla', 'ça (bu/o)'),
    AlphabetLetter('É', 'E accent aigu', 'e aigu', 'été (yaz)'),
  ];

  static const tr = <AlphabetLetter>[
    AlphabetLetter('A', 'A', 'a', 'araba'),
    AlphabetLetter('B', 'Be', 'be', 'balık'),
    AlphabetLetter('C', 'Ce', 'ce', 'cam'),
    AlphabetLetter('Ç', 'Çe', 'çe', 'çay'),
    AlphabetLetter('D', 'De', 'de', 'dere'),
    AlphabetLetter('E', 'E', 'e', 'elma'),
    AlphabetLetter('F', 'Fe', 'fe', 'fil'),
    AlphabetLetter('G', 'Ge', 'ge', 'gemi'),
    AlphabetLetter('Ğ', 'Yumuşak ge', 'yumuşak g', 'ağaç'),
    AlphabetLetter('H', 'He', 'he', 'havuç'),
    AlphabetLetter('I', 'I', 'ı', 'ışık'),
    AlphabetLetter('İ', 'İ', 'i', 'iplik'),
    AlphabetLetter('J', 'Je', 'je', 'jandarma'),
    AlphabetLetter('K', 'Ke', 'ke', 'kalem'),
    AlphabetLetter('L', 'Le', 'le', 'limon'),
    AlphabetLetter('M', 'Me', 'me', 'masa'),
    AlphabetLetter('N', 'Ne', 'ne', 'nar'),
    AlphabetLetter('O', 'O', 'o', 'orman'),
    AlphabetLetter('Ö', 'Ö', 'ö', 'ördek'),
    AlphabetLetter('P', 'Pe', 'pe', 'palto'),
    AlphabetLetter('R', 'Re', 're', 'resim'),
    AlphabetLetter('S', 'Se', 'se', 'su'),
    AlphabetLetter('Ş', 'Şe', 'şe', 'şeker'),
    AlphabetLetter('T', 'Te', 'te', 'tren'),
    AlphabetLetter('U', 'U', 'u', 'uzay'),
    AlphabetLetter('Ü', 'Ü', 'ü', 'üzüm'),
    AlphabetLetter('V', 'Ve', 've', 'vazo'),
    AlphabetLetter('Y', 'Ye', 'ye', 'yıldız'),
    AlphabetLetter('Z', 'Ze', 'ze', 'zeytin'),
  ];

  static List<AlphabetLetter> forLang(String code) {
    return switch (code) {
      'ar' => ar,
      'ru' => ru,
      'ja' => ja,
      'ko' => ko,
      'el' => el,
      'he' => he,
      'hi' => hi,
      'th' => th,
      'en' => en,
      'es' => es,
      'de' => de,
      'fr' => fr,
      'tr' => tr,
      _ => const [],
    };
  }

  static bool isRtl(String code) => code == 'ar' || code == 'he';
}
