// GENERATED — content batch F: AR / HE / FA, 9 missing A1 topics each.
// See docs/ICERIK_URETIM_BRIEFI.md for schema/tone rules. Not wired into
// Catalog yet — integration (import + _all list) happens centrally once all
// batches are delivered.
//
// LOWER-RESOURCE LANGUAGE WARNING: Arabic, Hebrew, and Farsi content in this
// file was generated by a model that is less reliable in these languages
// than in English/Spanish/French. Every single Scenario below is flagged
// with `// TODO: native review` and MUST be checked by a native speaker of
// each language (register/dialect, grammar, natural phrasing) before it is
// wired into the live Catalog or shipped to users.
// ignore_for_file: lines_longer_than_80_chars

import '../../models/models.dart';

final List<Scenario> catalogExtraBatchF = [
  // ===================== ARABIC (Modern Standard Arabic) =====================
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_intro',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Kendini tanıtmak', UiLang.en: 'Getting to know someone'},
    clipLine: 'مرحبًا، تشرفت بمعرفتك.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Arapçada meslek belirtirken "bir" anlamına gelen ayrı bir kelime kullanılmaz — isim doğrudan söylenir.',
        UiLang.en:
            'When stating a profession in Arabic, there is no separate word for "a/an" — the noun is stated directly.',
      },
      goodExample: 'أنا معلم.',
      badExample: 'أنا واحد معلم.',
    ),
    phrases: [
      Phrase(
        id: 'ar_intro_0',
        target: 'مرحبًا، تشرفت بمعرفتك.',
        gloss: {
          UiLang.tr: 'Merhaba, tanıştığımıza memnun oldum.',
          UiLang.en: 'Hello, nice to meet you.',
        },
      ),
      Phrase(
        id: 'ar_intro_1',
        target: 'ما اسمك؟',
        gloss: {UiLang.tr: 'Adınız nedir?', UiLang.en: "What's your name?"},
      ),
      Phrase(
        id: 'ar_intro_2',
        target: 'اسمي دنيز.',
        gloss: {UiLang.tr: 'Benim adım Deniz.', UiLang.en: 'My name is Deniz.'},
      ),
      Phrase(
        id: 'ar_intro_3',
        target: 'ما مهنتك؟',
        gloss: {UiLang.tr: 'Ne iş yapıyorsun?', UiLang.en: 'What do you do?'},
      ),
      Phrase(
        id: 'ar_intro_4',
        target: 'أنا معلم.',
        gloss: {UiLang.tr: 'Ben öğretmenim.', UiLang.en: 'I am a teacher.'},
      ),
      Phrase(
        id: 'ar_intro_5',
        target: 'من أين أنت؟',
        gloss: {UiLang.tr: 'Nerelisin?', UiLang.en: 'Where are you from?'},
      ),
      Phrase(
        id: 'ar_intro_6',
        target: 'إلى اللقاء.',
        gloss: {UiLang.tr: 'Görüşmek üzere.', UiLang.en: 'See you later.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Someone extends a hand.', expected: 'مرحبًا، تشرفت بمعرفتك.'),
      SpeakTurn(prompt: 'You want to know their name.', expected: 'ما اسمك؟'),
      SpeakTurn(prompt: 'They ask your name.', expected: 'اسمي دنيز.'),
      SpeakTurn(prompt: 'Small talk continues.', expected: 'ما مهنتك؟'),
      SpeakTurn(prompt: 'They ask about your job.', expected: 'أنا معلم.'),
      SpeakTurn(prompt: 'You want to know their origin.', expected: 'من أين أنت؟'),
      SpeakTurn(prompt: 'The conversation ends.', expected: 'إلى اللقاء.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_shopping',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Kıyafet alışverişi', UiLang.en: 'Clothes shopping'},
    clipLine: 'أبحث عن سترة.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'İşaret sıfatları isme cinsiyette uyar: eril isimler için هذا, dişil isimler için هذه kullanılır.',
        UiLang.en:
            'Demonstratives agree in gender with the noun: use هذا for masculine nouns and هذه for feminine nouns.',
      },
      goodExample: 'سآخذ هذه السترة.',
      badExample: 'سآخذ هذا السترة.',
    ),
    phrases: [
      Phrase(
        id: 'ar_shopping_0',
        target: 'أبحث عن سترة.',
        gloss: {UiLang.tr: 'Bir ceket arıyorum.', UiLang.en: "I'm looking for a jacket."},
      ),
      Phrase(
        id: 'ar_shopping_1',
        target: 'هل عندكم مقاس أكبر؟',
        gloss: {
          UiLang.tr: 'Daha büyük bedeniniz var mı?',
          UiLang.en: 'Do you have a bigger size?',
        },
      ),
      Phrase(
        id: 'ar_shopping_2',
        target: 'هل يمكنني تجربة هذه؟',
        gloss: {UiLang.tr: 'Bunu deneyebilir miyim?', UiLang.en: 'Can I try this on?'},
      ),
      Phrase(
        id: 'ar_shopping_3',
        target: 'غرفة القياس هناك.',
        gloss: {
          UiLang.tr: 'Deneme kabini şurada.',
          UiLang.en: 'The fitting room is over there.',
        },
      ),
      Phrase(
        id: 'ar_shopping_4',
        target: 'هل عندكم هذه باللون الأزرق؟',
        gloss: {UiLang.tr: 'Bunun mavisi var mı?', UiLang.en: 'Do you have this in blue?'},
      ),
      Phrase(
        id: 'ar_shopping_5',
        target: 'هل يوجد خصم؟',
        gloss: {UiLang.tr: 'İndirim var mı?', UiLang.en: 'Is there a discount?'},
      ),
      Phrase(
        id: 'ar_shopping_6',
        target: 'سآخذ هذه.',
        gloss: {UiLang.tr: 'Bunu alıyorum.', UiLang.en: "I'll take this one."},
      ),
      Phrase(
        id: 'ar_shopping_7',
        target: 'هل يمكنني الدفع بالبطاقة؟',
        gloss: {UiLang.tr: 'Kartla ödeyebilir miyim?', UiLang.en: 'Can I pay by card?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You enter a clothing store.', expected: 'أبحث عن سترة.'),
      SpeakTurn(prompt: 'It feels tight.', expected: 'هل عندكم مقاس أكبر؟'),
      SpeakTurn(prompt: 'You want to try the jacket.', expected: 'هل يمكنني تجربة هذه؟'),
      SpeakTurn(prompt: 'The clerk points.', expected: 'غرفة القياس هناك.'),
      SpeakTurn(prompt: 'You want another color.', expected: 'هل عندكم هذه باللون الأزرق؟'),
      SpeakTurn(prompt: 'You check the price.', expected: 'هل يوجد خصم؟'),
      SpeakTurn(prompt: 'You decide.', expected: 'سآخذ هذه.'),
      SpeakTurn(prompt: 'Time to pay.', expected: 'هل يمكنني الدفع بالبطاقة؟'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_numbers_time',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Sayılar ve saat', UiLang.en: 'Numbers and time'},
    clipLine: 'كم الساعة؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Saat söylerken asal sayı değil sıra sayısı kullanılır: "الساعة الثالثة" (üçüncü saat) gibi.',
        UiLang.en:
            "Telling time uses ordinal numbers, not cardinal numbers: \"الساعة الثالثة\" (the third hour) means three o'clock.",
      },
      goodExample: 'الساعة الثالثة.',
      badExample: 'الساعة ثلاثة.',
    ),
    phrases: [
      Phrase(
        id: 'ar_numbers_time_0',
        target: 'كم الساعة؟',
        gloss: {UiLang.tr: 'Saat kaç?', UiLang.en: 'What time is it?'},
      ),
      Phrase(
        id: 'ar_numbers_time_1',
        target: 'الساعة الثالثة.',
        gloss: {UiLang.tr: 'Saat üç.', UiLang.en: "It's three o'clock."},
      ),
      Phrase(
        id: 'ar_numbers_time_2',
        target: 'متى يفتح المحل؟',
        gloss: {
          UiLang.tr: 'Mağaza ne zaman açılıyor?',
          UiLang.en: 'What time does the store open?',
        },
      ),
      Phrase(
        id: 'ar_numbers_time_3',
        target: 'يفتح الساعة التاسعة صباحًا.',
        gloss: {
          UiLang.tr: 'Sabah dokuzda açılıyor.',
          UiLang.en: 'It opens at nine in the morning.',
        },
      ),
      Phrase(
        id: 'ar_numbers_time_4',
        target: 'عندي أخوان.',
        gloss: {UiLang.tr: 'İki erkek kardeşim var.', UiLang.en: 'I have two brothers.'},
      ),
      Phrase(
        id: 'ar_numbers_time_5',
        target: 'بكم هذا؟',
        gloss: {UiLang.tr: 'Bu kaça?', UiLang.en: 'How much is this?'},
      ),
      Phrase(
        id: 'ar_numbers_time_6',
        target: 'عشرون يورو.',
        gloss: {UiLang.tr: 'Yirmi euro.', UiLang.en: 'Twenty euros.'},
      ),
      Phrase(
        id: 'ar_numbers_time_7',
        target: 'أراك الساعة الخامسة.',
        gloss: {UiLang.tr: 'Saat beşte görüşürüz.', UiLang.en: 'See you at five.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You check the time.', expected: 'كم الساعة؟'),
      SpeakTurn(prompt: 'The clock shows three.', expected: 'الساعة الثالثة.'),
      SpeakTurn(prompt: 'You want to know opening hours.', expected: 'متى يفتح المحل؟'),
      SpeakTurn(prompt: 'The clerk explains.', expected: 'يفتح الساعة التاسعة صباحًا.'),
      SpeakTurn(prompt: 'Talking about family.', expected: 'عندي أخوان.'),
      SpeakTurn(prompt: 'You point at an item.', expected: 'بكم هذا؟'),
      SpeakTurn(prompt: 'The clerk answers.', expected: 'عشرون يورو.'),
      SpeakTurn(prompt: 'Saying goodbye.', expected: 'أراك الساعة الخامسة.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_family',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Aile', UiLang.en: 'Family'},
    clipLine: 'هذه عائلتي.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: '"Benim" anlamı için isme doğrudan ـي eki eklenir: أب+ي=أبي.',
        UiLang.en:
            'To say "my [noun]", attach the suffix ـي directly to the end of the noun: أب+ي=أبي (my father).',
      },
      goodExample: 'أبي طبيب.',
      badExample: 'أب أنا طبيب.',
    ),
    phrases: [
      Phrase(
        id: 'ar_family_0',
        target: 'هذه عائلتي.',
        gloss: {UiLang.tr: 'Bu benim ailem.', UiLang.en: 'This is my family.'},
      ),
      Phrase(
        id: 'ar_family_1',
        target: 'عندي أختان.',
        gloss: {UiLang.tr: 'İki kız kardeşim var.', UiLang.en: 'I have two sisters.'},
      ),
      Phrase(
        id: 'ar_family_2',
        target: 'أبي طبيب.',
        gloss: {UiLang.tr: 'Babam doktor.', UiLang.en: 'My father is a doctor.'},
      ),
      Phrase(
        id: 'ar_family_3',
        target: 'أمي تعمل في مستشفى.',
        gloss: {
          UiLang.tr: 'Annem hastanede çalışıyor.',
          UiLang.en: 'My mother works at a hospital.',
        },
      ),
      Phrase(
        id: 'ar_family_4',
        target: 'هل عندك إخوة؟',
        gloss: {UiLang.tr: 'Kardeşin var mı?', UiLang.en: 'Do you have any siblings?'},
      ),
      Phrase(
        id: 'ar_family_5',
        target: 'أنا الأصغر.',
        gloss: {UiLang.tr: 'Ben en küçüğüyüm.', UiLang.en: 'I am the youngest.'},
      ),
      Phrase(
        id: 'ar_family_6',
        target: 'جدتي تعيش معنا.',
        gloss: {UiLang.tr: 'Büyükannem bizimle yaşıyor.', UiLang.en: 'My grandmother lives with us.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You show a photo.', expected: 'هذه عائلتي.'),
      SpeakTurn(prompt: 'They ask about siblings.', expected: 'عندي أختان.'),
      SpeakTurn(prompt: 'Talking about parents.', expected: 'أبي طبيب.'),
      SpeakTurn(prompt: 'More about your mother.', expected: 'أمي تعمل في مستشفى.'),
      SpeakTurn(prompt: 'You ask them back.', expected: 'هل عندك إخوة؟'),
      SpeakTurn(prompt: 'They ask your birth order.', expected: 'أنا الأصغر.'),
      SpeakTurn(prompt: 'Talking about your household.', expected: 'جدتي تعيش معنا.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_weather',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Hava durumu', UiLang.en: 'Weather'},
    clipLine: 'كيف الجو اليوم؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Şimdiki zamanda hava tasviri için "olmak" fiiline gerek yoktur, sıfat doğrudan kullanılır.',
        UiLang.en:
            'Describing weather in the present needs no "to be" verb — the adjective is used directly: الجو مشمس ("the-weather sunny").',
      },
      goodExample: 'الجو مشمس.',
      badExample: 'الجو هو مشمس.',
    ),
    phrases: [
      Phrase(
        id: 'ar_weather_0',
        target: 'كيف الجو اليوم؟',
        gloss: {UiLang.tr: 'Bugün hava nasıl?', UiLang.en: "How's the weather today?"},
      ),
      Phrase(
        id: 'ar_weather_1',
        target: 'الجو مشمس اليوم.',
        gloss: {UiLang.tr: 'Bugün güneşli.', UiLang.en: "It's sunny today."},
      ),
      Phrase(
        id: 'ar_weather_2',
        target: 'إنها تمطر.',
        gloss: {UiLang.tr: 'Yağmur yağıyor.', UiLang.en: "It's raining."},
      ),
      Phrase(
        id: 'ar_weather_3',
        target: 'الجو بارد جدًا في الخارج.',
        gloss: {UiLang.tr: 'Dışarısı çok soğuk.', UiLang.en: "It's very cold outside."},
      ),
      Phrase(
        id: 'ar_weather_4',
        target: 'خذ مظلة معك.',
        gloss: {UiLang.tr: 'Yanına şemsiye al.', UiLang.en: 'Take an umbrella with you.'},
      ),
      Phrase(
        id: 'ar_weather_5',
        target: 'غدًا سيكون الجو أكثر دفئًا.',
        gloss: {
          UiLang.tr: 'Yarın hava daha sıcak olacak.',
          UiLang.en: 'Tomorrow the weather will be warmer.',
        },
      ),
      Phrase(
        id: 'ar_weather_6',
        target: 'أحب الأيام المشمسة.',
        gloss: {UiLang.tr: 'Güneşli günleri severim.', UiLang.en: 'I love sunny days.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Small talk opener.', expected: 'كيف الجو اليوم؟'),
      SpeakTurn(prompt: 'You look outside.', expected: 'الجو مشمس اليوم.'),
      SpeakTurn(prompt: 'Clouds gather.', expected: 'إنها تمطر.'),
      SpeakTurn(prompt: 'You step outside.', expected: 'الجو بارد جدًا في الخارج.'),
      SpeakTurn(prompt: 'You warn a friend.', expected: 'خذ مظلة معك.'),
      SpeakTurn(prompt: 'Checking the forecast.', expected: 'غدًا سيكون الجو أكثر دفئًا.'),
      SpeakTurn(prompt: 'Sharing your preference.', expected: 'أحب الأيام المشمسة.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_transport',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Toplu taşıma', UiLang.en: 'Public transport'},
    clipLine: 'أي حافلة تذهب إلى المركز؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Bir yere gitmek belirtilirken hedef isimden önce إلى ("-e/-a") edatı kullanılır.',
        UiLang.en: 'To express a destination, put إلى ("to") before the place noun.',
      },
      goodExample: 'تذكرة إلى المطار.',
      badExample: 'تذكرة المطار.',
    ),
    phrases: [
      Phrase(
        id: 'ar_transport_0',
        target: 'أي حافلة تذهب إلى المركز؟',
        gloss: {
          UiLang.tr: 'Hangi otobüs merkeze gidiyor?',
          UiLang.en: 'Which bus goes to the center?',
        },
      ),
      Phrase(
        id: 'ar_transport_1',
        target: 'تذكرة إلى المطار، من فضلك.',
        gloss: {
          UiLang.tr: 'Havalimanına bir bilet, lütfen.',
          UiLang.en: 'A ticket to the airport, please.',
        },
      ),
      Phrase(
        id: 'ar_transport_2',
        target: 'متى يغادر القطار القادم؟',
        gloss: {
          UiLang.tr: 'Sonraki tren saat kaçta kalkıyor?',
          UiLang.en: 'What time does the next train leave?',
        },
      ),
      Phrase(
        id: 'ar_transport_3',
        target: 'أين أقرب محطة مترو؟',
        gloss: {
          UiLang.tr: 'En yakın metro istasyonu nerede?',
          UiLang.en: 'Where is the nearest metro station?',
        },
      ),
      Phrase(
        id: 'ar_transport_4',
        target: 'هل هذا المقعد مشغول؟',
        gloss: {UiLang.tr: 'Bu koltuk dolu mu?', UiLang.en: 'Is this seat taken?'},
      ),
      Phrase(
        id: 'ar_transport_5',
        target: 'توقف هنا من فضلك.',
        gloss: {UiLang.tr: 'Lütfen burada durun.', UiLang.en: 'Please stop here.'},
      ),
      Phrase(
        id: 'ar_transport_6',
        target: 'كم من الوقت يستغرق؟',
        gloss: {UiLang.tr: 'Ne kadar sürer?', UiLang.en: 'How long does it take?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You are at a bus stop.', expected: 'أي حافلة تذهب إلى المركز؟'),
      SpeakTurn(prompt: 'At the ticket counter.', expected: 'تذكرة إلى المطار، من فضلك.'),
      SpeakTurn(prompt: 'Checking the schedule.', expected: 'متى يغادر القطار القادم؟'),
      SpeakTurn(prompt: 'You are lost.', expected: 'أين أقرب محطة مترو؟'),
      SpeakTurn(prompt: 'You want to sit down.', expected: 'هل هذا المقعد مشغول؟'),
      SpeakTurn(prompt: 'You are in a taxi.', expected: 'توقف هنا من فضلك.'),
      SpeakTurn(prompt: 'Asking about the trip.', expected: 'كم من الوقت يستغرق؟'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_emergency',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Acil durum', UiLang.en: 'Emergency'},
    clipLine: 'النجدة!',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Arapçada emir kipi kime seslenildiğine göre değişir: tek erkeğe اتصل، tek kadına اتصلي، bir gruba اتصلوا — kalabalığa seslenirken çoğul biçim gerekir.',
        UiLang.en:
            'Arabic commands change form depending on who you address: اتصل (one man), اتصلي (one woman), اتصلوا (a group) — shouting to a crowd for help requires the plural form.',
      },
      goodExample: 'اتصلوا بالإسعاف!',
      badExample: 'اتصل بالإسعاف!',
    ),
    phrases: [
      Phrase(
        id: 'ar_emergency_0',
        target: 'النجدة!',
        gloss: {UiLang.tr: 'İmdat!', UiLang.en: 'Help!'},
      ),
      Phrase(
        id: 'ar_emergency_1',
        target: 'اتصلوا بالإسعاف!',
        gloss: {UiLang.tr: 'Ambulans çağırın!', UiLang.en: 'Call an ambulance!'},
      ),
      Phrase(
        id: 'ar_emergency_2',
        target: 'أحتاج إلى طبيب.',
        gloss: {UiLang.tr: 'Bir doktora ihtiyacım var.', UiLang.en: 'I need a doctor.'},
      ),
      Phrase(
        id: 'ar_emergency_3',
        target: 'أين أقرب مستشفى؟',
        gloss: {UiLang.tr: 'En yakın hastane nerede?', UiLang.en: 'Where is the nearest hospital?'},
      ),
      Phrase(
        id: 'ar_emergency_4',
        target: 'فقدت جواز سفري.',
        gloss: {UiLang.tr: 'Pasaportumu kaybettim.', UiLang.en: 'I lost my passport.'},
      ),
      Phrase(
        id: 'ar_emergency_5',
        target: 'اتصلوا بالشرطة من فضلكم.',
        gloss: {UiLang.tr: 'Lütfen polisi arayın.', UiLang.en: 'Please call the police.'},
      ),
      Phrase(
        id: 'ar_emergency_6',
        target: 'أشعر بأنني مريض جدًا.',
        gloss: {UiLang.tr: 'Kendimi çok kötü hissediyorum.', UiLang.en: 'I feel very sick.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Something goes wrong.', expected: 'النجدة!'),
      SpeakTurn(prompt: 'Someone collapses.', expected: 'اتصلوا بالإسعاف!'),
      SpeakTurn(prompt: 'You feel unwell.', expected: 'أحتاج إلى طبيب.'),
      SpeakTurn(prompt: 'You ask a stranger.', expected: 'أين أقرب مستشفى؟'),
      SpeakTurn(prompt: 'At the police station.', expected: 'فقدت جواز سفري.'),
      SpeakTurn(prompt: 'There has been a theft.', expected: 'اتصلوا بالشرطة من فضلكم.'),
      SpeakTurn(prompt: 'You describe how you feel.', expected: 'أشعر بأنني مريض جدًا.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_routine',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Günlük rutin', UiLang.en: 'Daily routine'},
    clipLine: 'أستيقظ الساعة السابعة كل يوم.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            '"Ben" özneli şimdiki zaman fiilleri fiil köküne eklenen أ ön ekiyle başlar: أستيقظ، أذهب، أنام.',
        UiLang.en:
            'Present-tense "I" verbs begin with the prefix أ attached to the verb stem: أستيقظ (I wake up), أذهب (I go), أنام (I sleep).',
      },
      goodExample: 'أستيقظ الساعة السابعة.',
      badExample: 'يستيقظ الساعة السابعة.',
    ),
    phrases: [
      Phrase(
        id: 'ar_routine_0',
        target: 'أستيقظ الساعة السابعة كل يوم.',
        gloss: {UiLang.tr: 'Her gün saat yedide uyanırım.', UiLang.en: 'I wake up at seven every day.'},
      ),
      Phrase(
        id: 'ar_routine_1',
        target: 'أتناول الفطور الساعة الثامنة.',
        gloss: {UiLang.tr: 'Sekizde kahvaltı yaparım.', UiLang.en: 'I have breakfast at eight.'},
      ),
      Phrase(
        id: 'ar_routine_2',
        target: 'أذهب إلى العمل بالحافلة.',
        gloss: {UiLang.tr: 'Otobüsle işe giderim.', UiLang.en: 'I go to work by bus.'},
      ),
      Phrase(
        id: 'ar_routine_3',
        target: 'أنهي عملي الساعة الخامسة.',
        gloss: {UiLang.tr: 'İşimi saat beşte bitiririm.', UiLang.en: 'I finish my work at five.'},
      ),
      Phrase(
        id: 'ar_routine_4',
        target: 'في المساء أطبخ العشاء.',
        gloss: {UiLang.tr: 'Akşamları yemek pişiririm.', UiLang.en: 'In the evening I cook dinner.'},
      ),
      Phrase(
        id: 'ar_routine_5',
        target: 'أنام الساعة الحادية عشرة.',
        gloss: {UiLang.tr: 'Saat on birde uyurum.', UiLang.en: 'I sleep at eleven.'},
      ),
      Phrase(
        id: 'ar_routine_6',
        target: 'في عطلة نهاية الأسبوع أستيقظ متأخرًا.',
        gloss: {UiLang.tr: 'Hafta sonları geç kalkarım.', UiLang.en: 'On weekends I wake up late.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Describing your morning.', expected: 'أستيقظ الساعة السابعة كل يوم.'),
      SpeakTurn(prompt: 'What do you do next?', expected: 'أتناول الفطور الساعة الثامنة.'),
      SpeakTurn(prompt: 'How do you commute?', expected: 'أذهب إلى العمل بالحافلة.'),
      SpeakTurn(prompt: 'When does your day end?', expected: 'أنهي عملي الساعة الخامسة.'),
      SpeakTurn(prompt: 'What about the evening?', expected: 'في المساء أطبخ العشاء.'),
      SpeakTurn(prompt: 'When do you go to bed?', expected: 'أنام الساعة الحادية عشرة.'),
      SpeakTurn(prompt: 'What about weekends?', expected: 'في عطلة نهاية الأسبوع أستيقظ متأخرًا.'),
    ],
  ),
  // TODO: native review — MSA register, natural phrasing, grammar.
  Scenario(
    id: 'ar_past_story',
    lang: LearnLang.ar,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Geçmişte bir gün anlatmak', UiLang.en: 'Telling a story in the past'},
    clipLine: 'أمس ذهبت إلى السوق.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Geçmiş zamanda "ben" öznesi için fiil sonuna ـتُ eki eklenir: ذهبتُ، شربتُ، عدتُ، نمتُ.',
        UiLang.en:
            'Past-tense "I" verbs take the suffix ـتُ at the end: ذهبتُ (I went), شربتُ (I drank), عدتُ (I returned), نمتُ (I slept).',
      },
      goodExample: 'ذهبتُ إلى السوق.',
      badExample: 'أنا ذهب إلى السوق.',
    ),
    phrases: [
      Phrase(
        id: 'ar_past_story_0',
        target: 'أمس ذهبت إلى السوق.',
        gloss: {UiLang.tr: 'Dün markete gittim.', UiLang.en: 'Yesterday I went to the market.'},
      ),
      Phrase(
        id: 'ar_past_story_1',
        target: 'قابلت صديقًا هناك.',
        gloss: {UiLang.tr: 'Orada bir arkadaşımla karşılaştım.', UiLang.en: 'I met a friend there.'},
      ),
      Phrase(
        id: 'ar_past_story_2',
        target: 'شربنا القهوة معًا.',
        gloss: {UiLang.tr: 'Birlikte kahve içtik.', UiLang.en: 'We drank coffee together.'},
      ),
      Phrase(
        id: 'ar_past_story_3',
        target: 'ثم عدت إلى البيت.',
        gloss: {UiLang.tr: 'Sonra eve döndüm.', UiLang.en: 'Then I returned home.'},
      ),
      Phrase(
        id: 'ar_past_story_4',
        target: 'كنت متعبًا جدًا.',
        gloss: {UiLang.tr: 'Çok yorgundum.', UiLang.en: 'I was very tired.'},
      ),
      Phrase(
        id: 'ar_past_story_5',
        target: 'نمت مبكرًا.',
        gloss: {UiLang.tr: 'Erken uyudum.', UiLang.en: 'I slept early.'},
      ),
      Phrase(
        id: 'ar_past_story_6',
        target: 'كان يومًا جميلًا.',
        gloss: {UiLang.tr: 'Güzel bir gündü.', UiLang.en: 'It was a beautiful day.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Tell what happened yesterday.', expected: 'أمس ذهبت إلى السوق.'),
      SpeakTurn(prompt: 'Who did you see?', expected: 'قابلت صديقًا هناك.'),
      SpeakTurn(prompt: 'What did you do together?', expected: 'شربنا القهوة معًا.'),
      SpeakTurn(prompt: 'What happened next?', expected: 'ثم عدت إلى البيت.'),
      SpeakTurn(prompt: 'How did you feel?', expected: 'كنت متعبًا جدًا.'),
      SpeakTurn(prompt: 'What did you do after that?', expected: 'نمت مبكرًا.'),
      SpeakTurn(prompt: 'Sum up the day.', expected: 'كان يومًا جميلًا.'),
    ],
  ),

  // ===================== HEBREW =====================
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_intro',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Kendini tanıtmak', UiLang.en: 'Getting to know someone'},
    clipLine: 'שלום, נעים מאוד.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'İbranicede şimdiki zamanda "olmak" fiili yoktur — özne ve yüklem art arda söylenir.',
        UiLang.en:
            'Hebrew has no present-tense verb "to be" — the subject and predicate are simply placed next to each other: אני מורה ("I teacher" = I am a teacher).',
      },
      goodExample: 'אני מורה.',
      badExample: 'אני יש מורה.',
    ),
    phrases: [
      Phrase(
        id: 'he_intro_0',
        target: 'שלום, נעים מאוד.',
        gloss: {
          UiLang.tr: 'Merhaba, tanıştığımıza memnun oldum.',
          UiLang.en: 'Hello, nice to meet you.',
        },
      ),
      Phrase(
        id: 'he_intro_1',
        target: 'מה שמך?',
        gloss: {UiLang.tr: 'Adın ne?', UiLang.en: "What's your name?"},
      ),
      Phrase(
        id: 'he_intro_2',
        target: 'שמי דניז.',
        gloss: {UiLang.tr: 'Benim adım Deniz.', UiLang.en: 'My name is Deniz.'},
      ),
      Phrase(
        id: 'he_intro_3',
        target: 'במה אתה עובד?',
        gloss: {UiLang.tr: 'Ne iş yapıyorsun?', UiLang.en: 'What do you do?'},
      ),
      Phrase(
        id: 'he_intro_4',
        target: 'אני מורה.',
        gloss: {UiLang.tr: 'Ben öğretmenim.', UiLang.en: 'I am a teacher.'},
      ),
      Phrase(
        id: 'he_intro_5',
        target: 'מאיפה אתה?',
        gloss: {UiLang.tr: 'Nerelisin?', UiLang.en: 'Where are you from?'},
      ),
      Phrase(
        id: 'he_intro_6',
        target: 'להתראות.',
        gloss: {UiLang.tr: 'Görüşmek üzere.', UiLang.en: 'See you later.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Someone extends a hand.', expected: 'שלום, נעים מאוד.'),
      SpeakTurn(prompt: 'You want to know their name.', expected: 'מה שמך?'),
      SpeakTurn(prompt: 'They ask your name.', expected: 'שמי דניז.'),
      SpeakTurn(prompt: 'Small talk continues.', expected: 'במה אתה עובד?'),
      SpeakTurn(prompt: 'They ask about your job.', expected: 'אני מורה.'),
      SpeakTurn(prompt: 'You want to know their origin.', expected: 'מאיפה אתה?'),
      SpeakTurn(prompt: 'The conversation ends.', expected: 'להתראות.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_shopping',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Kıyafet alışverişi', UiLang.en: 'Clothes shopping'},
    clipLine: 'אני מחפש ז׳קט.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Belirlilik takısı ה, isme boşluksuz doğrudan eklenir.',
        UiLang.en:
            'The definite article ה attaches directly to the front of the noun, with no space and no separate word.',
      },
      goodExample: 'חדר ההלבשה.',
      badExample: 'חדר ה הלבשה.',
    ),
    phrases: [
      Phrase(
        id: 'he_shopping_0',
        target: 'אני מחפש ז׳קט.',
        gloss: {UiLang.tr: 'Bir ceket arıyorum.', UiLang.en: "I'm looking for a jacket."},
      ),
      Phrase(
        id: 'he_shopping_1',
        target: 'יש לכם את זה במידה גדולה יותר?',
        gloss: {
          UiLang.tr: 'Bunun daha büyük bedeni var mı?',
          UiLang.en: 'Do you have this in a bigger size?',
        },
      ),
      Phrase(
        id: 'he_shopping_2',
        target: 'אפשר למדוד את זה?',
        gloss: {UiLang.tr: 'Bunu deneyebilir miyim?', UiLang.en: 'Can I try this on?'},
      ),
      Phrase(
        id: 'he_shopping_3',
        target: 'חדר ההלבשה שם.',
        gloss: {
          UiLang.tr: 'Deneme kabini şurada.',
          UiLang.en: 'The fitting room is over there.',
        },
      ),
      Phrase(
        id: 'he_shopping_4',
        target: 'יש לכם את זה בכחול?',
        gloss: {UiLang.tr: 'Bunun mavisi var mı?', UiLang.en: 'Do you have this in blue?'},
      ),
      Phrase(
        id: 'he_shopping_5',
        target: 'יש הנחה?',
        gloss: {UiLang.tr: 'İndirim var mı?', UiLang.en: 'Is there a discount?'},
      ),
      Phrase(
        id: 'he_shopping_6',
        target: 'אני אקח את זה.',
        gloss: {UiLang.tr: 'Bunu alıyorum.', UiLang.en: "I'll take this one."},
      ),
      Phrase(
        id: 'he_shopping_7',
        target: 'אפשר לשלם בכרטיס אשראי?',
        gloss: {UiLang.tr: 'Kartla ödeyebilir miyim?', UiLang.en: 'Can I pay by credit card?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You enter a clothing store.', expected: 'אני מחפש ז׳קט.'),
      SpeakTurn(prompt: 'It feels tight.', expected: 'יש לכם את זה במידה גדולה יותר?'),
      SpeakTurn(prompt: 'You want to try the jacket.', expected: 'אפשר למדוד את זה?'),
      SpeakTurn(prompt: 'The clerk points.', expected: 'חדר ההלבשה שם.'),
      SpeakTurn(prompt: 'You want another color.', expected: 'יש לכם את זה בכחול?'),
      SpeakTurn(prompt: 'You check the price.', expected: 'יש הנחה?'),
      SpeakTurn(prompt: 'You decide.', expected: 'אני אקח את זה.'),
      SpeakTurn(prompt: 'Time to pay.', expected: 'אפשר לשלם בכרטיס אשראי?'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_numbers_time',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Sayılar ve saat', UiLang.en: 'Numbers and time'},
    clipLine: 'מה השעה?',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Saat söylerken sayının dişil biçimi kullanılır çünkü "שעה" (saat) dişil bir isimdir.',
        UiLang.en:
            'Telling time uses the feminine form of the number, because שעה ("hour") is a feminine noun.',
      },
      goodExample: 'נתראה בשתיים.',
      badExample: 'נתראה בשניים.',
    ),
    phrases: [
      Phrase(
        id: 'he_numbers_time_0',
        target: 'מה השעה?',
        gloss: {UiLang.tr: 'Saat kaç?', UiLang.en: 'What time is it?'},
      ),
      Phrase(
        id: 'he_numbers_time_1',
        target: 'השעה שלוש.',
        gloss: {UiLang.tr: 'Saat üç.', UiLang.en: "It's three o'clock."},
      ),
      Phrase(
        id: 'he_numbers_time_2',
        target: 'באיזו שעה החנות נפתחת?',
        gloss: {
          UiLang.tr: 'Mağaza ne zaman açılıyor?',
          UiLang.en: 'What time does the store open?',
        },
      ),
      Phrase(
        id: 'he_numbers_time_3',
        target: 'היא נפתחת בתשע בבוקר.',
        gloss: {
          UiLang.tr: 'Sabah dokuzda açılıyor.',
          UiLang.en: 'It opens at nine in the morning.',
        },
      ),
      Phrase(
        id: 'he_numbers_time_4',
        target: 'יש לי שני אחים.',
        gloss: {UiLang.tr: 'İki erkek kardeşim var.', UiLang.en: 'I have two brothers.'},
      ),
      Phrase(
        id: 'he_numbers_time_5',
        target: 'כמה זה עולה?',
        gloss: {UiLang.tr: 'Bu ne kadar?', UiLang.en: 'How much is this?'},
      ),
      Phrase(
        id: 'he_numbers_time_6',
        target: 'עשרים יורו.',
        gloss: {UiLang.tr: 'Yirmi euro.', UiLang.en: 'Twenty euros.'},
      ),
      Phrase(
        id: 'he_numbers_time_7',
        target: 'נתראה בחמש.',
        gloss: {UiLang.tr: 'Saat beşte görüşürüz.', UiLang.en: 'See you at five.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You check the time.', expected: 'מה השעה?'),
      SpeakTurn(prompt: 'The clock shows three.', expected: 'השעה שלוש.'),
      SpeakTurn(prompt: 'You want to know opening hours.', expected: 'באיזו שעה החנות נפתחת?'),
      SpeakTurn(prompt: 'The clerk explains.', expected: 'היא נפתחת בתשע בבוקר.'),
      SpeakTurn(prompt: 'Talking about family.', expected: 'יש לי שני אחים.'),
      SpeakTurn(prompt: 'You point at an item.', expected: 'כמה זה עולה?'),
      SpeakTurn(prompt: 'The clerk answers.', expected: 'עשרים יורו.'),
      SpeakTurn(prompt: 'Saying goodbye.', expected: 'נתראה בחמש.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_family',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Aile', UiLang.en: 'Family'},
    clipLine: 'זאת המשפחה שלי.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: '"Benim" anlamı için שלי sözcüğü, ismin arkasına yerleştirilir.',
        UiLang.en:
            'To say "my [noun]", place שלי after the noun: אבא שלי ("father of-mine" = my father).',
      },
      goodExample: 'אבא שלי רופא.',
      badExample: 'שלי אבא רופא.',
    ),
    phrases: [
      Phrase(
        id: 'he_family_0',
        target: 'זאת המשפחה שלי.',
        gloss: {UiLang.tr: 'Bu benim ailem.', UiLang.en: 'This is my family.'},
      ),
      Phrase(
        id: 'he_family_1',
        target: 'יש לי שתי אחיות.',
        gloss: {UiLang.tr: 'İki kız kardeşim var.', UiLang.en: 'I have two sisters.'},
      ),
      Phrase(
        id: 'he_family_2',
        target: 'אבא שלי רופא.',
        gloss: {UiLang.tr: 'Babam doktor.', UiLang.en: 'My father is a doctor.'},
      ),
      Phrase(
        id: 'he_family_3',
        target: 'אמא שלי עובדת בבית חולים.',
        gloss: {
          UiLang.tr: 'Annem hastanede çalışıyor.',
          UiLang.en: 'My mother works at a hospital.',
        },
      ),
      Phrase(
        id: 'he_family_4',
        target: 'יש לך אחים?',
        gloss: {UiLang.tr: 'Kardeşin var mı?', UiLang.en: 'Do you have any siblings?'},
      ),
      Phrase(
        id: 'he_family_5',
        target: 'אני הכי צעיר.',
        gloss: {UiLang.tr: 'Ben en küçüğüyüm.', UiLang.en: 'I am the youngest.'},
      ),
      Phrase(
        id: 'he_family_6',
        target: 'סבתא שלי גרה איתנו.',
        gloss: {UiLang.tr: 'Büyükannem bizimle yaşıyor.', UiLang.en: 'My grandmother lives with us.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You show a photo.', expected: 'זאת המשפחה שלי.'),
      SpeakTurn(prompt: 'They ask about siblings.', expected: 'יש לי שתי אחיות.'),
      SpeakTurn(prompt: 'Talking about parents.', expected: 'אבא שלי רופא.'),
      SpeakTurn(prompt: 'More about your mother.', expected: 'אמא שלי עובדת בבית חולים.'),
      SpeakTurn(prompt: 'You ask them back.', expected: 'יש לך אחים?'),
      SpeakTurn(prompt: 'They ask your birth order.', expected: 'אני הכי צעיר.'),
      SpeakTurn(prompt: 'Talking about your household.', expected: 'סבתא שלי גרה איתנו.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_weather',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Hava durumu', UiLang.en: 'Weather'},
    clipLine: 'איך מזג האוויר היום?',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: '"Güneşli" demek için sıfat değil, יש ("var") + isim kalıbı kullanılır: יש שמש ("güneş var").',
        UiLang.en:
            "\"It's sunny\" is expressed with יש (\"there is\") + a noun, not an adjective: יש שמש (\"there is sun\").",
      },
      goodExample: 'יש שמש היום.',
      badExample: 'זה שמש היום.',
    ),
    phrases: [
      Phrase(
        id: 'he_weather_0',
        target: 'איך מזג האוויר היום?',
        gloss: {UiLang.tr: 'Bugün hava nasıl?', UiLang.en: "How's the weather today?"},
      ),
      Phrase(
        id: 'he_weather_1',
        target: 'יש שמש היום.',
        gloss: {UiLang.tr: 'Bugün güneşli.', UiLang.en: "It's sunny today."},
      ),
      Phrase(
        id: 'he_weather_2',
        target: 'יורד גשם.',
        gloss: {UiLang.tr: 'Yağmur yağıyor.', UiLang.en: "It's raining."},
      ),
      Phrase(
        id: 'he_weather_3',
        target: 'קר מאוד בחוץ.',
        gloss: {UiLang.tr: 'Dışarısı çok soğuk.', UiLang.en: "It's very cold outside."},
      ),
      Phrase(
        id: 'he_weather_4',
        target: 'קח מטריה.',
        gloss: {UiLang.tr: 'Şemsiye al.', UiLang.en: 'Take an umbrella.'},
      ),
      Phrase(
        id: 'he_weather_5',
        target: 'מחר יהיה יותר חם.',
        gloss: {UiLang.tr: 'Yarın hava daha sıcak olacak.', UiLang.en: 'Tomorrow it will be warmer.'},
      ),
      Phrase(
        id: 'he_weather_6',
        target: 'אני אוהב ימים שמשיים.',
        gloss: {UiLang.tr: 'Güneşli günleri severim.', UiLang.en: 'I love sunny days.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Small talk opener.', expected: 'איך מזג האוויר היום?'),
      SpeakTurn(prompt: 'You look outside.', expected: 'יש שמש היום.'),
      SpeakTurn(prompt: 'Clouds gather.', expected: 'יורד גשם.'),
      SpeakTurn(prompt: 'You step outside.', expected: 'קר מאוד בחוץ.'),
      SpeakTurn(prompt: 'You warn a friend.', expected: 'קח מטריה.'),
      SpeakTurn(prompt: 'Checking the forecast.', expected: 'מחר יהיה יותר חם.'),
      SpeakTurn(prompt: 'Sharing your preference.', expected: 'אני אוהב ימים שמשיים.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_transport',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Toplu taşıma', UiLang.en: 'Public transport'},
    clipLine: 'איזה אוטובוס נוסע למרכז?',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Bir yere gitmek belirtilirken ל ("-e/-a") öneki, yer isminin başına doğrudan eklenir.',
        UiLang.en: 'To express a destination, the prefix ל ("to") attaches directly to the front of the place noun.',
      },
      goodExample: 'כרטיס לשדה התעופה.',
      badExample: 'כרטיס ל שדה התעופה.',
    ),
    phrases: [
      Phrase(
        id: 'he_transport_0',
        target: 'איזה אוטובוס נוסע למרכז?',
        gloss: {
          UiLang.tr: 'Hangi otobüs merkeze gidiyor?',
          UiLang.en: 'Which bus goes to the center?',
        },
      ),
      Phrase(
        id: 'he_transport_1',
        target: 'כרטיס לשדה התעופה, בבקשה.',
        gloss: {
          UiLang.tr: 'Havalimanına bir bilet, lütfen.',
          UiLang.en: 'A ticket to the airport, please.',
        },
      ),
      Phrase(
        id: 'he_transport_2',
        target: 'באיזו שעה יוצאת הרכבת הבאה?',
        gloss: {
          UiLang.tr: 'Sonraki tren saat kaçta kalkıyor?',
          UiLang.en: 'What time does the next train leave?',
        },
      ),
      Phrase(
        id: 'he_transport_3',
        target: 'איפה תחנת המטרו הקרובה?',
        gloss: {
          UiLang.tr: 'En yakın metro istasyonu nerede?',
          UiLang.en: 'Where is the nearest metro station?',
        },
      ),
      Phrase(
        id: 'he_transport_4',
        target: 'המקום הזה תפוס?',
        gloss: {UiLang.tr: 'Bu koltuk dolu mu?', UiLang.en: 'Is this seat taken?'},
      ),
      Phrase(
        id: 'he_transport_5',
        target: 'תעצור כאן, בבקשה.',
        gloss: {UiLang.tr: 'Lütfen burada durun.', UiLang.en: 'Please stop here.'},
      ),
      Phrase(
        id: 'he_transport_6',
        target: 'כמה זמן זה לוקח?',
        gloss: {UiLang.tr: 'Ne kadar sürer?', UiLang.en: 'How long does it take?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You are at a bus stop.', expected: 'איזה אוטובוס נוסע למרכז?'),
      SpeakTurn(prompt: 'At the ticket counter.', expected: 'כרטיס לשדה התעופה, בבקשה.'),
      SpeakTurn(prompt: 'Checking the schedule.', expected: 'באיזו שעה יוצאת הרכבת הבאה?'),
      SpeakTurn(prompt: 'You are lost.', expected: 'איפה תחנת המטרו הקרובה?'),
      SpeakTurn(prompt: 'You want to sit down.', expected: 'המקום הזה תפוס?'),
      SpeakTurn(prompt: 'You are in a taxi.', expected: 'תעצור כאן, בבקשה.'),
      SpeakTurn(prompt: 'Asking about the trip.', expected: 'כמה זמן זה לוקח?'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_emergency',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Acil durum', UiLang.en: 'Emergency'},
    clipLine: 'הצילו!',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Günlük konuşmada emirler genellikle gelecek zaman fiil biçimiyle ifade edilir: תתקשרו ("arayacaksınız" = "arayın").',
        UiLang.en:
            'Everyday commands are often expressed with the future-tense verb form instead of a true imperative: תתקשרו ("you will call" = "call!").',
      },
      goodExample: 'תתקשרו למשטרה!',
      badExample: 'להתקשר למשטרה!',
    ),
    phrases: [
      Phrase(
        id: 'he_emergency_0',
        target: 'הצילו!',
        gloss: {UiLang.tr: 'İmdat!', UiLang.en: 'Help!'},
      ),
      Phrase(
        id: 'he_emergency_1',
        target: 'תתקשרו לאמבולנס!',
        gloss: {UiLang.tr: 'Ambulans çağırın!', UiLang.en: 'Call an ambulance!'},
      ),
      Phrase(
        id: 'he_emergency_2',
        target: 'אני צריך רופא.',
        gloss: {UiLang.tr: 'Bir doktora ihtiyacım var.', UiLang.en: 'I need a doctor.'},
      ),
      Phrase(
        id: 'he_emergency_3',
        target: 'איפה בית החולים הקרוב?',
        gloss: {UiLang.tr: 'En yakın hastane nerede?', UiLang.en: 'Where is the nearest hospital?'},
      ),
      Phrase(
        id: 'he_emergency_4',
        target: 'איבדתי את הדרכון שלי.',
        gloss: {UiLang.tr: 'Pasaportumu kaybettim.', UiLang.en: 'I lost my passport.'},
      ),
      Phrase(
        id: 'he_emergency_5',
        target: 'תתקשרו למשטרה, בבקשה.',
        gloss: {UiLang.tr: 'Lütfen polisi arayın.', UiLang.en: 'Please call the police.'},
      ),
      Phrase(
        id: 'he_emergency_6',
        target: 'אני מרגיש ממש רע.',
        gloss: {UiLang.tr: 'Kendimi çok kötü hissediyorum.', UiLang.en: 'I feel very sick.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Something goes wrong.', expected: 'הצילו!'),
      SpeakTurn(prompt: 'Someone collapses.', expected: 'תתקשרו לאמבולנס!'),
      SpeakTurn(prompt: 'You feel unwell.', expected: 'אני צריך רופא.'),
      SpeakTurn(prompt: 'You ask a stranger.', expected: 'איפה בית החולים הקרוב?'),
      SpeakTurn(prompt: 'At the police station.', expected: 'איבדתי את הדרכון שלי.'),
      SpeakTurn(prompt: 'There has been a theft.', expected: 'תתקשרו למשטרה, בבקשה.'),
      SpeakTurn(prompt: 'You describe how you feel.', expected: 'אני מרגיש ממש רע.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_routine',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Günlük rutin', UiLang.en: 'Daily routine'},
    clipLine: 'אני קם בשבע כל יום.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Şimdiki zaman fiilleri, "ben" öznesinde bile konuşanın cinsiyetine göre değişir: אני קם (erkek) / אני קמה (kadın).',
        UiLang.en:
            "Present-tense verbs change ending based on the speaker's gender, even for \"I\": אני קם (a man says \"I wake up\") vs אני קמה (a woman says it).",
      },
      goodExample: 'אני קמה בשבע.',
      badExample: 'אני קם בשבע.',
    ),
    phrases: [
      Phrase(
        id: 'he_routine_0',
        target: 'אני קם בשבע כל יום.',
        gloss: {UiLang.tr: 'Her gün saat yedide uyanırım.', UiLang.en: 'I wake up at seven every day.'},
      ),
      Phrase(
        id: 'he_routine_1',
        target: 'אני אוכל ארוחת בוקר בשמונה.',
        gloss: {UiLang.tr: 'Sekizde kahvaltı yaparım.', UiLang.en: 'I eat breakfast at eight.'},
      ),
      Phrase(
        id: 'he_routine_2',
        target: 'אני נוסע לעבודה באוטובוס.',
        gloss: {UiLang.tr: 'Otobüsle işe giderim.', UiLang.en: 'I go to work by bus.'},
      ),
      Phrase(
        id: 'he_routine_3',
        target: 'אני מסיים לעבוד בחמש.',
        gloss: {UiLang.tr: 'İşimi saat beşte bitiririm.', UiLang.en: 'I finish work at five.'},
      ),
      Phrase(
        id: 'he_routine_4',
        target: 'בערב אני מבשל ארוחת ערב.',
        gloss: {UiLang.tr: 'Akşamları yemek pişiririm.', UiLang.en: 'In the evening I cook dinner.'},
      ),
      Phrase(
        id: 'he_routine_5',
        target: 'אני הולך לישון באחת עשרה.',
        gloss: {UiLang.tr: 'Saat on birde yatarım.', UiLang.en: 'I go to sleep at eleven.'},
      ),
      Phrase(
        id: 'he_routine_6',
        target: 'בסופי שבוע אני קם מאוחר.',
        gloss: {UiLang.tr: 'Hafta sonları geç kalkarım.', UiLang.en: 'On weekends I wake up late.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Describing your morning.', expected: 'אני קם בשבע כל יום.'),
      SpeakTurn(prompt: 'What do you do next?', expected: 'אני אוכל ארוחת בוקר בשמונה.'),
      SpeakTurn(prompt: 'How do you commute?', expected: 'אני נוסע לעבודה באוטובוס.'),
      SpeakTurn(prompt: 'When does your day end?', expected: 'אני מסיים לעבוד בחמש.'),
      SpeakTurn(prompt: 'What about the evening?', expected: 'בערב אני מבשל ארוחת ערב.'),
      SpeakTurn(prompt: 'When do you go to bed?', expected: 'אני הולך לישון באחת עשרה.'),
      SpeakTurn(prompt: 'What about weekends?', expected: 'בסופי שבוע אני קם מאוחר.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'he_past_story',
    lang: LearnLang.he,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Geçmişte bir gün anlatmak', UiLang.en: 'Telling a story in the past'},
    clipLine: 'אתמול הלכתי לשוק.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Geçmiş zamanda "ben" öznesi için fiil sonuna תי eki eklenir: הלכתי, פגשתי, שתיתי.',
        UiLang.en:
            'Hebrew past-tense "I" verbs end in תי: הלכתי (I went), פגשתי (I met), שתיתי (I drank).',
      },
      goodExample: 'הלכתי לשוק.',
      badExample: 'אני הלך לשוק.',
    ),
    phrases: [
      Phrase(
        id: 'he_past_story_0',
        target: 'אתמול הלכתי לשוק.',
        gloss: {UiLang.tr: 'Dün markete gittim.', UiLang.en: 'Yesterday I went to the market.'},
      ),
      Phrase(
        id: 'he_past_story_1',
        target: 'פגשתי שם חבר.',
        gloss: {UiLang.tr: 'Orada bir arkadaşımla karşılaştım.', UiLang.en: 'I met a friend there.'},
      ),
      Phrase(
        id: 'he_past_story_2',
        target: 'שתינו קפה ביחד.',
        gloss: {UiLang.tr: 'Birlikte kahve içtik.', UiLang.en: 'We drank coffee together.'},
      ),
      Phrase(
        id: 'he_past_story_3',
        target: 'אחר כך חזרתי הביתה.',
        gloss: {UiLang.tr: 'Sonra eve döndüm.', UiLang.en: 'Then I went back home.'},
      ),
      Phrase(
        id: 'he_past_story_4',
        target: 'הייתי מאוד עייף.',
        gloss: {UiLang.tr: 'Çok yorgundum.', UiLang.en: 'I was very tired.'},
      ),
      Phrase(
        id: 'he_past_story_5',
        target: 'הלכתי לישון מוקדם.',
        gloss: {UiLang.tr: 'Erken uyudum.', UiLang.en: 'I went to sleep early.'},
      ),
      Phrase(
        id: 'he_past_story_6',
        target: 'זה היה יום נחמד.',
        gloss: {UiLang.tr: 'Güzel bir gündü.', UiLang.en: 'It was a nice day.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Tell what happened yesterday.', expected: 'אתמול הלכתי לשוק.'),
      SpeakTurn(prompt: 'Who did you see?', expected: 'פגשתי שם חבר.'),
      SpeakTurn(prompt: 'What did you do together?', expected: 'שתינו קפה ביחד.'),
      SpeakTurn(prompt: 'What happened next?', expected: 'אחר כך חזרתי הביתה.'),
      SpeakTurn(prompt: 'How did you feel?', expected: 'הייתי מאוד עייף.'),
      SpeakTurn(prompt: 'What did you do after that?', expected: 'הלכתי לישון מוקדם.'),
      SpeakTurn(prompt: 'Sum up the day.', expected: 'זה היה יום נחמד.'),
    ],
  ),

  // ===================== FARSI (Persian) =====================
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_intro',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Kendini tanıtmak', UiLang.en: 'Getting to know someone'},
    clipLine: 'سلام، از آشنایی‌تان خوشبختم.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Yeni tanıştığın biriyle resmi "شما" (siz) kullanılır, günlük "تو" (sen) değil — fiil çekimi de buna göre değişir.',
        UiLang.en:
            'Use the formal "شما" (you) with someone you just met, not the informal "تو" — the verb ending changes accordingly (هستید vs هستی).',
      },
      goodExample: 'شما اهل کجا هستید؟',
      badExample: 'تو اهل کجا هستی؟',
    ),
    phrases: [
      Phrase(
        id: 'fa_intro_0',
        target: 'سلام، از آشنایی‌تان خوشبختم.',
        gloss: {
          UiLang.tr: 'Merhaba, tanıştığımıza memnun oldum.',
          UiLang.en: 'Hello, nice to meet you.',
        },
      ),
      Phrase(
        id: 'fa_intro_1',
        target: 'اسم شما چیست؟',
        gloss: {UiLang.tr: 'Adınız nedir?', UiLang.en: "What's your name?"},
      ),
      Phrase(
        id: 'fa_intro_2',
        target: 'اسم من دنیز است.',
        gloss: {UiLang.tr: 'Benim adım Deniz.', UiLang.en: 'My name is Deniz.'},
      ),
      Phrase(
        id: 'fa_intro_3',
        target: 'شغل شما چیست؟',
        gloss: {UiLang.tr: 'Ne iş yapıyorsunuz?', UiLang.en: 'What do you do?'},
      ),
      Phrase(
        id: 'fa_intro_4',
        target: 'من معلم هستم.',
        gloss: {UiLang.tr: 'Ben öğretmenim.', UiLang.en: 'I am a teacher.'},
      ),
      Phrase(
        id: 'fa_intro_5',
        target: 'شما اهل کجا هستید؟',
        gloss: {UiLang.tr: 'Nerelisiniz?', UiLang.en: 'Where are you from?'},
      ),
      Phrase(
        id: 'fa_intro_6',
        target: 'خداحافظ.',
        gloss: {UiLang.tr: 'Hoşça kalın.', UiLang.en: 'Goodbye.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Someone extends a hand.', expected: 'سلام، از آشنایی‌تان خوشبختم.'),
      SpeakTurn(prompt: 'You want to know their name.', expected: 'اسم شما چیست؟'),
      SpeakTurn(prompt: 'They ask your name.', expected: 'اسم من دنیز است.'),
      SpeakTurn(prompt: 'Small talk continues.', expected: 'شغل شما چیست؟'),
      SpeakTurn(prompt: 'They ask about your job.', expected: 'من معلم هستم.'),
      SpeakTurn(prompt: 'You want to know their origin.', expected: 'شما اهل کجا هستید؟'),
      SpeakTurn(prompt: 'The conversation ends.', expected: 'خداحافظ.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_shopping',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Kıyafet alışverişi', UiLang.en: 'Clothes shopping'},
    clipLine: 'دنبال یک ژاکت می‌گردم.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Karşılaştırma sıfatı, sıfatın sonuna ـتر eklenerek yapılır: بزرگ (büyük) → بزرگ‌تر (daha büyük).',
        UiLang.en: 'Comparative adjectives are formed by adding ـتر to the adjective: بزرگ (big) → بزرگ‌تر (bigger).',
      },
      goodExample: 'سایز بزرگ‌تر دارید؟',
      badExample: 'سایز خیلی بزرگ دارید؟',
    ),
    phrases: [
      Phrase(
        id: 'fa_shopping_0',
        target: 'دنبال یک ژاکت می‌گردم.',
        gloss: {UiLang.tr: 'Bir ceket arıyorum.', UiLang.en: "I'm looking for a jacket."},
      ),
      Phrase(
        id: 'fa_shopping_1',
        target: 'سایز بزرگ‌تر دارید؟',
        gloss: {
          UiLang.tr: 'Daha büyük bedeniniz var mı?',
          UiLang.en: 'Do you have a bigger size?',
        },
      ),
      Phrase(
        id: 'fa_shopping_2',
        target: 'می‌توانم این را امتحان کنم؟',
        gloss: {UiLang.tr: 'Bunu deneyebilir miyim?', UiLang.en: 'Can I try this on?'},
      ),
      Phrase(
        id: 'fa_shopping_3',
        target: 'اتاق پرو آن‌جاست.',
        gloss: {
          UiLang.tr: 'Deneme kabini şurada.',
          UiLang.en: 'The fitting room is over there.',
        },
      ),
      Phrase(
        id: 'fa_shopping_4',
        target: 'این را آبی هم دارید؟',
        gloss: {UiLang.tr: 'Bunun mavisi var mı?', UiLang.en: 'Do you have this in blue too?'},
      ),
      Phrase(
        id: 'fa_shopping_5',
        target: 'تخفیف دارد؟',
        gloss: {UiLang.tr: 'İndirim var mı?', UiLang.en: 'Is there a discount?'},
      ),
      Phrase(
        id: 'fa_shopping_6',
        target: 'این را برمی‌دارم.',
        gloss: {UiLang.tr: 'Bunu alıyorum.', UiLang.en: "I'll take this one."},
      ),
      Phrase(
        id: 'fa_shopping_7',
        target: 'می‌توانم با کارت پرداخت کنم؟',
        gloss: {UiLang.tr: 'Kartla ödeyebilir miyim?', UiLang.en: 'Can I pay by card?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You enter a clothing store.', expected: 'دنبال یک ژاکت می‌گردم.'),
      SpeakTurn(prompt: 'It feels tight.', expected: 'سایز بزرگ‌تر دارید؟'),
      SpeakTurn(prompt: 'You want to try the jacket.', expected: 'می‌توانم این را امتحان کنم؟'),
      SpeakTurn(prompt: 'The clerk points.', expected: 'اتاق پرو آن‌جاست.'),
      SpeakTurn(prompt: 'You want another color.', expected: 'این را آبی هم دارید؟'),
      SpeakTurn(prompt: 'You check the price.', expected: 'تخفیف دارد؟'),
      SpeakTurn(prompt: 'You decide.', expected: 'این را برمی‌دارم.'),
      SpeakTurn(prompt: 'Time to pay.', expected: 'می‌توانم با کارت پرداخت کنم؟'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_numbers_time',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 8,
    titles: {UiLang.tr: 'Sayılar ve saat', UiLang.en: 'Numbers and time'},
    clipLine: 'ساعت چند است؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Saat sormak için "ساعت چند است؟" denir, cevap verirken sayı ساعت kelimesinin hemen ardından gelir.',
        UiLang.en:
            'To ask the time say "ساعت چند است؟" and when answering, put the number right after ساعت: ساعت + number + است.',
      },
      goodExample: 'ساعت سه است.',
      badExample: 'سه ساعت است.',
    ),
    phrases: [
      Phrase(
        id: 'fa_numbers_time_0',
        target: 'ساعت چند است؟',
        gloss: {UiLang.tr: 'Saat kaç?', UiLang.en: 'What time is it?'},
      ),
      Phrase(
        id: 'fa_numbers_time_1',
        target: 'ساعت سه است.',
        gloss: {UiLang.tr: 'Saat üç.', UiLang.en: "It's three o'clock."},
      ),
      Phrase(
        id: 'fa_numbers_time_2',
        target: 'مغازه ساعت چند باز می‌شود؟',
        gloss: {
          UiLang.tr: 'Mağaza saat kaçta açılıyor?',
          UiLang.en: 'What time does the store open?',
        },
      ),
      Phrase(
        id: 'fa_numbers_time_3',
        target: 'ساعت نه صبح باز می‌شود.',
        gloss: {
          UiLang.tr: 'Sabah dokuzda açılıyor.',
          UiLang.en: 'It opens at nine in the morning.',
        },
      ),
      Phrase(
        id: 'fa_numbers_time_4',
        target: 'من دو برادر دارم.',
        gloss: {UiLang.tr: 'İki erkek kardeşim var.', UiLang.en: 'I have two brothers.'},
      ),
      Phrase(
        id: 'fa_numbers_time_5',
        target: 'این چند است؟',
        gloss: {UiLang.tr: 'Bu ne kadar?', UiLang.en: 'How much is this?'},
      ),
      Phrase(
        id: 'fa_numbers_time_6',
        target: 'بیست یورو.',
        gloss: {UiLang.tr: 'Yirmi euro.', UiLang.en: 'Twenty euros.'},
      ),
      Phrase(
        id: 'fa_numbers_time_7',
        target: 'ساعت پنج می‌بینمت.',
        gloss: {UiLang.tr: 'Saat beşte görüşürüz.', UiLang.en: 'See you at five.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You check the time.', expected: 'ساعت چند است؟'),
      SpeakTurn(prompt: 'The clock shows three.', expected: 'ساعت سه است.'),
      SpeakTurn(prompt: 'You want to know opening hours.', expected: 'مغازه ساعت چند باز می‌شود؟'),
      SpeakTurn(prompt: 'The clerk explains.', expected: 'ساعت نه صبح باز می‌شود.'),
      SpeakTurn(prompt: 'Talking about family.', expected: 'من دو برادر دارم.'),
      SpeakTurn(prompt: 'You point at an item.', expected: 'این چند است؟'),
      SpeakTurn(prompt: 'The clerk answers.', expected: 'بیست یورو.'),
      SpeakTurn(prompt: 'Saying goodbye.', expected: 'ساعت پنج می‌بینمت.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_family',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Aile', UiLang.en: 'Family'},
    clipLine: 'این خانواده‌ی من است.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: '"Benim" anlamı için isme doğrudan ـم eki eklenir: پدر+م=پدرم.',
        UiLang.en:
            'To say "my [noun]", attach the suffix ـم directly to the noun: پدر+م=پدرم (my father).',
      },
      goodExample: 'پدرم دکتر است.',
      badExample: 'من پدر دکتر است.',
    ),
    phrases: [
      Phrase(
        id: 'fa_family_0',
        target: 'این خانواده‌ی من است.',
        gloss: {UiLang.tr: 'Bu benim ailem.', UiLang.en: 'This is my family.'},
      ),
      Phrase(
        id: 'fa_family_1',
        target: 'من دو خواهر دارم.',
        gloss: {UiLang.tr: 'İki kız kardeşim var.', UiLang.en: 'I have two sisters.'},
      ),
      Phrase(
        id: 'fa_family_2',
        target: 'پدرم دکتر است.',
        gloss: {UiLang.tr: 'Babam doktor.', UiLang.en: 'My father is a doctor.'},
      ),
      Phrase(
        id: 'fa_family_3',
        target: 'مادرم در بیمارستان کار می‌کند.',
        gloss: {
          UiLang.tr: 'Annem hastanede çalışıyor.',
          UiLang.en: 'My mother works at a hospital.',
        },
      ),
      Phrase(
        id: 'fa_family_4',
        target: 'تو خواهر یا برادر داری؟',
        gloss: {UiLang.tr: 'Kardeşin var mı?', UiLang.en: 'Do you have any siblings?'},
      ),
      Phrase(
        id: 'fa_family_5',
        target: 'من کوچک‌ترین هستم.',
        gloss: {UiLang.tr: 'Ben en küçüğüyüm.', UiLang.en: 'I am the youngest.'},
      ),
      Phrase(
        id: 'fa_family_6',
        target: 'مادربزرگم با ما زندگی می‌کند.',
        gloss: {UiLang.tr: 'Büyükannem bizimle yaşıyor.', UiLang.en: 'My grandmother lives with us.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You show a photo.', expected: 'این خانواده‌ی من است.'),
      SpeakTurn(prompt: 'They ask about siblings.', expected: 'من دو خواهر دارم.'),
      SpeakTurn(prompt: 'Talking about parents.', expected: 'پدرم دکتر است.'),
      SpeakTurn(prompt: 'More about your mother.', expected: 'مادرم در بیمارستان کار می‌کند.'),
      SpeakTurn(prompt: 'You ask them back.', expected: 'تو خواهر یا برادر داری؟'),
      SpeakTurn(prompt: 'They ask your birth order.', expected: 'من کوچک‌ترین هستم.'),
      SpeakTurn(prompt: 'Talking about your household.', expected: 'مادربزرگم با ما زندگی می‌کند.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_weather',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Hava durumu', UiLang.en: 'Weather'},
    clipLine: 'امروز هوا چطور است؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            '"Yağmur yağıyor" ifadesi, öznesi باران (yağmur) olan bir cümledir; "o" anlamına gelen ayrı bir özne kullanılmaz.',
        UiLang.en:
            '"It\'s raining" literally says "rain is pouring" — باران (rain) is the grammatical subject; there is no dummy "it".',
      },
      goodExample: 'باران می‌بارد.',
      badExample: 'آن باران می‌بارد.',
    ),
    phrases: [
      Phrase(
        id: 'fa_weather_0',
        target: 'امروز هوا چطور است؟',
        gloss: {UiLang.tr: 'Bugün hava nasıl?', UiLang.en: "How's the weather today?"},
      ),
      Phrase(
        id: 'fa_weather_1',
        target: 'امروز هوا آفتابی است.',
        gloss: {UiLang.tr: 'Bugün güneşli.', UiLang.en: "It's sunny today."},
      ),
      Phrase(
        id: 'fa_weather_2',
        target: 'باران می‌بارد.',
        gloss: {UiLang.tr: 'Yağmur yağıyor.', UiLang.en: "It's raining."},
      ),
      Phrase(
        id: 'fa_weather_3',
        target: 'بیرون خیلی سرد است.',
        gloss: {UiLang.tr: 'Dışarısı çok soğuk.', UiLang.en: "It's very cold outside."},
      ),
      Phrase(
        id: 'fa_weather_4',
        target: 'چتر بردار.',
        gloss: {UiLang.tr: 'Şemsiye al.', UiLang.en: 'Take an umbrella.'},
      ),
      Phrase(
        id: 'fa_weather_5',
        target: 'فردا هوا گرم‌تر می‌شود.',
        gloss: {
          UiLang.tr: 'Yarın hava daha sıcak olacak.',
          UiLang.en: 'Tomorrow the weather will be warmer.',
        },
      ),
      Phrase(
        id: 'fa_weather_6',
        target: 'من روزهای آفتابی را دوست دارم.',
        gloss: {UiLang.tr: 'Güneşli günleri severim.', UiLang.en: 'I love sunny days.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Small talk opener.', expected: 'امروز هوا چطور است؟'),
      SpeakTurn(prompt: 'You look outside.', expected: 'امروز هوا آفتابی است.'),
      SpeakTurn(prompt: 'Clouds gather.', expected: 'باران می‌بارد.'),
      SpeakTurn(prompt: 'You step outside.', expected: 'بیرون خیلی سرد است.'),
      SpeakTurn(prompt: 'You warn a friend.', expected: 'چتر بردار.'),
      SpeakTurn(prompt: 'Checking the forecast.', expected: 'فردا هوا گرم‌تر می‌شود.'),
      SpeakTurn(prompt: 'Sharing your preference.', expected: 'من روزهای آفتابی را دوست دارم.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_transport',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Toplu taşıma', UiLang.en: 'Public transport'},
    clipLine: 'کدام اتوبوس به مرکز شهر می‌رود؟',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Bir yere gitmek belirtilirken hedef isimden önce به ("-e/-a") edatı kullanılır.',
        UiLang.en: 'To express a destination, put به ("to") before the place noun.',
      },
      goodExample: 'بلیت به فرودگاه.',
      badExample: 'بلیت فرودگاه.',
    ),
    phrases: [
      Phrase(
        id: 'fa_transport_0',
        target: 'کدام اتوبوس به مرکز شهر می‌رود؟',
        gloss: {
          UiLang.tr: 'Hangi otobüs şehir merkezine gidiyor?',
          UiLang.en: 'Which bus goes to the city center?',
        },
      ),
      Phrase(
        id: 'fa_transport_1',
        target: 'یک بلیت به فرودگاه، لطفاً.',
        gloss: {
          UiLang.tr: 'Havalimanına bir bilet, lütfen.',
          UiLang.en: 'A ticket to the airport, please.',
        },
      ),
      Phrase(
        id: 'fa_transport_2',
        target: 'قطار بعدی ساعت چند حرکت می‌کند؟',
        gloss: {
          UiLang.tr: 'Sonraki tren saat kaçta kalkıyor?',
          UiLang.en: 'What time does the next train leave?',
        },
      ),
      Phrase(
        id: 'fa_transport_3',
        target: 'نزدیک‌ترین ایستگاه مترو کجاست؟',
        gloss: {
          UiLang.tr: 'En yakın metro istasyonu nerede?',
          UiLang.en: 'Where is the nearest metro station?',
        },
      ),
      Phrase(
        id: 'fa_transport_4',
        target: 'این صندلی خالی است؟',
        gloss: {UiLang.tr: 'Bu koltuk boş mu?', UiLang.en: 'Is this seat free?'},
      ),
      Phrase(
        id: 'fa_transport_5',
        target: 'لطفاً این‌جا نگه دارید.',
        gloss: {UiLang.tr: 'Lütfen burada durun.', UiLang.en: 'Please stop here.'},
      ),
      Phrase(
        id: 'fa_transport_6',
        target: 'چقدر طول می‌کشد؟',
        gloss: {UiLang.tr: 'Ne kadar sürer?', UiLang.en: 'How long does it take?'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'You are at a bus stop.', expected: 'کدام اتوبوس به مرکز شهر می‌رود؟'),
      SpeakTurn(prompt: 'At the ticket counter.', expected: 'یک بلیت به فرودگاه، لطفاً.'),
      SpeakTurn(prompt: 'Checking the schedule.', expected: 'قطار بعدی ساعت چند حرکت می‌کند؟'),
      SpeakTurn(prompt: 'You are lost.', expected: 'نزدیک‌ترین ایستگاه مترو کجاست؟'),
      SpeakTurn(prompt: 'You want to sit down.', expected: 'این صندلی خالی است؟'),
      SpeakTurn(prompt: 'You are in a taxi.', expected: 'لطفاً این‌جا نگه دارید.'),
      SpeakTurn(prompt: 'Asking about the trip.', expected: 'چقدر طول می‌کشد؟'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_emergency',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Acil durum', UiLang.en: 'Emergency'},
    clipLine: 'کمک!',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Nazik/resmi emir kipi fiil kökü + ید ekiyle yapılır: خبر کنید ("haber verin/çağırın").',
        UiLang.en: 'The polite/plural command form is the verb stem + ید: خبر کنید ("call!" — polite).',
      },
      goodExample: 'پلیس را خبر کنید!',
      badExample: 'پلیس را خبر کن!',
    ),
    phrases: [
      Phrase(
        id: 'fa_emergency_0',
        target: 'کمک!',
        gloss: {UiLang.tr: 'İmdat!', UiLang.en: 'Help!'},
      ),
      Phrase(
        id: 'fa_emergency_1',
        target: 'آمبولانس خبر کنید!',
        gloss: {UiLang.tr: 'Ambulans çağırın!', UiLang.en: 'Call an ambulance!'},
      ),
      Phrase(
        id: 'fa_emergency_2',
        target: 'من به دکتر احتیاج دارم.',
        gloss: {UiLang.tr: 'Bir doktora ihtiyacım var.', UiLang.en: 'I need a doctor.'},
      ),
      Phrase(
        id: 'fa_emergency_3',
        target: 'نزدیک‌ترین بیمارستان کجاست؟',
        gloss: {UiLang.tr: 'En yakın hastane nerede?', UiLang.en: 'Where is the nearest hospital?'},
      ),
      Phrase(
        id: 'fa_emergency_4',
        target: 'پاسپورتم را گم کردم.',
        gloss: {UiLang.tr: 'Pasaportumu kaybettim.', UiLang.en: 'I lost my passport.'},
      ),
      Phrase(
        id: 'fa_emergency_5',
        target: 'لطفاً پلیس را خبر کنید.',
        gloss: {UiLang.tr: 'Lütfen polisi arayın.', UiLang.en: 'Please call the police.'},
      ),
      Phrase(
        id: 'fa_emergency_6',
        target: 'حالم خیلی بد است.',
        gloss: {UiLang.tr: 'Kendimi çok kötü hissediyorum.', UiLang.en: 'I feel very sick.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Something goes wrong.', expected: 'کمک!'),
      SpeakTurn(prompt: 'Someone collapses.', expected: 'آمبولانس خبر کنید!'),
      SpeakTurn(prompt: 'You feel unwell.', expected: 'من به دکتر احتیاج دارم.'),
      SpeakTurn(prompt: 'You ask a stranger.', expected: 'نزدیک‌ترین بیمارستان کجاست؟'),
      SpeakTurn(prompt: 'At the police station.', expected: 'پاسپورتم را گم کردم.'),
      SpeakTurn(prompt: 'There has been a theft.', expected: 'لطفاً پلیس را خبر کنید.'),
      SpeakTurn(prompt: 'You describe how you feel.', expected: 'حالم خیلی بد است.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_routine',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Günlük rutin', UiLang.en: 'Daily routine'},
    clipLine: 'من هر روز ساعت هفت بیدار می‌شوم.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr: 'Şimdiki zaman/alışkanlık bildiren fiillerde köke می- ön eki eklenir: می‌روم، می‌خورم، می‌خوابم.',
        UiLang.en: 'The prefix می- before the verb stem marks the habitual present tense: می‌روم (I go), می‌خورم (I eat), می‌خوابم (I sleep).',
      },
      goodExample: 'هر روز بیدار می‌شوم.',
      badExample: 'هر روز بیدار شوم.',
    ),
    phrases: [
      Phrase(
        id: 'fa_routine_0',
        target: 'من هر روز ساعت هفت بیدار می‌شوم.',
        gloss: {UiLang.tr: 'Her gün saat yedide uyanırım.', UiLang.en: 'I wake up at seven every day.'},
      ),
      Phrase(
        id: 'fa_routine_1',
        target: 'ساعت هشت صبحانه می‌خورم.',
        gloss: {UiLang.tr: 'Sekizde kahvaltı yaparım.', UiLang.en: 'I have breakfast at eight.'},
      ),
      Phrase(
        id: 'fa_routine_2',
        target: 'با اتوبوس به سر کار می‌روم.',
        gloss: {UiLang.tr: 'Otobüsle işe giderim.', UiLang.en: 'I go to work by bus.'},
      ),
      Phrase(
        id: 'fa_routine_3',
        target: 'ساعت پنج کارم را تمام می‌کنم.',
        gloss: {UiLang.tr: 'İşimi saat beşte bitiririm.', UiLang.en: 'I finish my work at five.'},
      ),
      Phrase(
        id: 'fa_routine_4',
        target: 'عصرها شام درست می‌کنم.',
        gloss: {UiLang.tr: 'Akşamları yemek pişiririm.', UiLang.en: 'In the evenings I make dinner.'},
      ),
      Phrase(
        id: 'fa_routine_5',
        target: 'ساعت یازده می‌خوابم.',
        gloss: {UiLang.tr: 'Saat on birde uyurum.', UiLang.en: 'I go to sleep at eleven.'},
      ),
      Phrase(
        id: 'fa_routine_6',
        target: 'آخر هفته‌ها دیر بیدار می‌شوم.',
        gloss: {UiLang.tr: 'Hafta sonları geç kalkarım.', UiLang.en: 'On weekends I wake up late.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Describing your morning.', expected: 'من هر روز ساعت هفت بیدار می‌شوم.'),
      SpeakTurn(prompt: 'What do you do next?', expected: 'ساعت هشت صبحانه می‌خورم.'),
      SpeakTurn(prompt: 'How do you commute?', expected: 'با اتوبوس به سر کار می‌روم.'),
      SpeakTurn(prompt: 'When does your day end?', expected: 'ساعت پنج کارم را تمام می‌کنم.'),
      SpeakTurn(prompt: 'What about the evening?', expected: 'عصرها شام درست می‌کنم.'),
      SpeakTurn(prompt: 'When do you go to bed?', expected: 'ساعت یازده می‌خوابم.'),
      SpeakTurn(prompt: 'What about weekends?', expected: 'آخر هفته‌ها دیر بیدار می‌شوم.'),
    ],
  ),
  // TODO: native review — register, natural phrasing, grammar.
  Scenario(
    id: 'fa_past_story',
    lang: LearnLang.fa,
    cefr: Cefr.a1,
    minutes: 7,
    titles: {UiLang.tr: 'Geçmişte bir gün anlatmak', UiLang.en: 'Telling a story in the past'},
    clipLine: 'دیروز به بازار رفتم.',
    grammarNote: GrammarNote(
      rule: {
        UiLang.tr:
            'Basit geçmiş zaman geçmiş kökü + kişi ekiyle yapılır; "ben" için ek ـم"dir, yardımcı fiil gerekmez: رفتم، خوردم، بودم.',
        UiLang.en:
            'The simple past = past stem + personal ending; for "I" the ending is ـم, no helping verb needed: رفتم (I went), خوردم (I drank/ate), بودم (I was).',
      },
      goodExample: 'دیروز به بازار رفتم.',
      badExample: 'دیروز به بازار می‌روم.',
    ),
    phrases: [
      Phrase(
        id: 'fa_past_story_0',
        target: 'دیروز به بازار رفتم.',
        gloss: {UiLang.tr: 'Dün markete gittim.', UiLang.en: 'Yesterday I went to the market.'},
      ),
      Phrase(
        id: 'fa_past_story_1',
        target: 'آن‌جا یک دوست دیدم.',
        gloss: {UiLang.tr: 'Orada bir arkadaşımla karşılaştım.', UiLang.en: 'I saw a friend there.'},
      ),
      Phrase(
        id: 'fa_past_story_2',
        target: 'با هم قهوه خوردیم.',
        gloss: {UiLang.tr: 'Birlikte kahve içtik.', UiLang.en: 'We drank coffee together.'},
      ),
      Phrase(
        id: 'fa_past_story_3',
        target: 'بعد به خانه برگشتم.',
        gloss: {UiLang.tr: 'Sonra eve döndüm.', UiLang.en: 'Then I went back home.'},
      ),
      Phrase(
        id: 'fa_past_story_4',
        target: 'خیلی خسته بودم.',
        gloss: {UiLang.tr: 'Çok yorgundum.', UiLang.en: 'I was very tired.'},
      ),
      Phrase(
        id: 'fa_past_story_5',
        target: 'زود خوابیدم.',
        gloss: {UiLang.tr: 'Erken uyudum.', UiLang.en: 'I slept early.'},
      ),
      Phrase(
        id: 'fa_past_story_6',
        target: 'روز خوبی بود.',
        gloss: {UiLang.tr: 'Güzel bir gündü.', UiLang.en: 'It was a good day.'},
      ),
    ],
    turns: [
      SpeakTurn(prompt: 'Tell what happened yesterday.', expected: 'دیروز به بازار رفتم.'),
      SpeakTurn(prompt: 'Who did you see?', expected: 'آن‌جا یک دوست دیدم.'),
      SpeakTurn(prompt: 'What did you do together?', expected: 'با هم قهوه خوردیم.'),
      SpeakTurn(prompt: 'What happened next?', expected: 'بعد به خانه برگشتم.'),
      SpeakTurn(prompt: 'How did you feel?', expected: 'خیلی خسته بودم.'),
      SpeakTurn(prompt: 'What did you do after that?', expected: 'زود خوابیدم.'),
      SpeakTurn(prompt: 'Sum up the day.', expected: 'روز خوبی بود.'),
    ],
  ),
];
